# Import modules

In [1]:
from TabArenaIterator import TabArenaIterator
import pandas as pd
import numpy as np
import plotly.express as px
import json
import plotly.graph_objects as go

# Iterate all TabArena datasets for the density plots

In [2]:
# Read previously saved results (calculated from getDensityTable.ipynb / section 'Iteration of all datasets from TabArena')
final_table = pd.read_csv('./data folder/results files/final_table.csv')
all_densities = json.load( open( "./data folder/results files/all_densities.json" ) )
display(final_table)
#all_densities

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,initial_XGB_normalized_accuracy,final_XGB_r2,final_XGB_accuracy,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy
0,46904,airfoil_self_noise,5,4,1503,1503,1.051902e-03,0.110450,NaN,0.950645,...,NaN,0.923800,NaN,NaN,0.947991,NaN,NaN,0.928413,NaN,NaN
1,46905,Amazon_employee_access,9,1,32769,67,5.433146e-21,1.000000,NaN,NaN,...,0.884447,NaN,NaN,NaN,NaN,0.944563,0.889126,NaN,NaN,NaN
2,46906,anneal,38,13,886,9,6.763895e-16,0.140625,bf,NaN,...,0.976852,NaN,NaN,NaN,NaN,0.992593,0.990741,NaN,NaN,NaN
3,46907,Another-Dataset-on-used-Fiat-500,7,3,1515,34,5.646737e-10,0.354167,NaN,0.830676,...,NaN,-0.180396,NaN,NaN,0.836072,NaN,NaN,-0.064585,NaN,NaN
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.984474,NaN,0.937500,0.875000,NaN,0.992325,0.984649,NaN,0.750000,0.500000
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.784577,NaN,0.886842,0.773684,NaN,0.895827,0.791654,NaN,0.888158,0.776316
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.714000,NaN,0.801843,0.603687,NaN,0.847333,0.694667,NaN,0.806452,0.612903
7,46912,Bioresponse,1776,9,3751,87,0.000000e+00,0.169922,D1736,NaN,...,0.548845,NaN,0.629630,0.259259,NaN,0.761989,0.523979,NaN,0.629630,0.259259
8,46913,blood-transfusion-service-center,4,2,502,188,1.906424e-04,0.183773,NaN,NaN,...,0.440000,NaN,NaN,NaN,NaN,0.733333,0.466667,NaN,NaN,NaN
9,46915,churn,19,5,5000,625,2.774980e-36,0.248016,international_plan,NaN,...,0.910667,NaN,0.771277,0.542553,NaN,0.918667,0.837333,NaN,0.792553,0.585106
10,46916,coil2000_insurance_policies,85,6,8261,17,4.188386e-67,0.177083,contributionBicyclePolicies,NaN,...,0.867662,NaN,NaN,NaN,NaN,0.933152,0.866305,NaN,NaN,NaN
11,46917,concrete_compressive_strength,8,2,996,452,3.038551e-15,0.208295,NaN,0.867073,...,NaN,NaN,NaN,NaN,0.884803,NaN,NaN,NaN,NaN,NaN
12,46918,credit-g,20,7,1000,128,1.403353e-13,0.148148,people_liable,NaN,...,0.473333,NaN,0.666667,0.333333,NaN,0.720000,0.440000,NaN,0.717949,0.435897
13,46919,credit_card_clients_default,23,4,29944,201,4.928384e-57,0.358929,SEX,NaN,...,0.642889,NaN,0.590164,0.180328,NaN,0.818778,0.637556,NaN,0.688525,0.377049
14,46920,customer_satisfaction_in_airline,21,8,129880,16181,1.861241e-18,0.208089,CustomerType,NaN,...,0.909814,NaN,0.793615,0.587230,NaN,0.947105,0.894210,NaN,0.798764,0.597528
15,46921,diabetes,8,2,768,283,1.117498e-13,0.354193,NaN,NaN,...,0.532468,NaN,NaN,NaN,NaN,0.761905,0.523810,NaN,NaN,NaN
16,46922,Diabetes130US,47,9,71518,9,7.578438e-37,0.140625,tolazamide,NaN,...,0.828020,NaN,NaN,NaN,NaN,0.914010,0.828020,NaN,NaN,NaN
17,46923,diamonds,9,3,53595,276,2.616387e-13,0.985714,NaN,0.981644,...,NaN,-0.048643,NaN,NaN,0.977045,NaN,NaN,-0.026704,NaN,NaN
18,46924,E-CommereShippingData,10,7,10999,4761,9.032578e-09,0.220417,Gender,NaN,...,0.343636,NaN,0.592022,0.184045,NaN,0.670303,0.340606,NaN,0.599020,0.198041
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.528889,NaN,0.754717,0.509434,NaN,0.802222,0.604444,NaN,0.811321,0.622642
20,46928,Food_Delivery_Time,9,4,45242,3221,5.407391e-16,0.326806,NaN,0.376339,...,NaN,0.503811,NaN,NaN,0.312180,NaN,NaN,0.461866,NaN,NaN
21,46929,GiveMeSomeCredit,10,3,149354,323,1.066472e-19,0.119453,FinancialDistressNextTwoYears,NaN,...,0.871867,NaN,0.659794,0.319588,NaN,0.934778,0.869556,NaN,0.639175,0.278351
22,46930,hazelnut-spread-contaminant-detection,30,1,2400,781,4.281294e-90,1.000000,NaN,NaN,...,0.836111,NaN,NaN,NaN,NaN,0.931944,0.863889,NaN,NaN,NaN
23,46931,healthcare_insurance_expenses,6,5,1335,986,5.399227e-04,0.218528,sex,0.806058,...,NaN,0.614456,NaN,NaN,0.803626,NaN,NaN,0.610852,NaN,NaN
24,46932,heloc,23,3,9871,184,1.483257e-35,0.135294,RiskPerformance,NaN,...,0.454430,NaN,0.714286,0.428571,NaN,0.715424,0.430848,NaN,0.714286,0.428571
25,46933,hiva_agnostic,1617,9,3825,55,0.000000e+00,0.107422,molecule_structure_property_1609,NaN,...,0.944107,NaN,0.823529,0.735294,NaN,0.962738,0.944107,NaN,0.823529,0.735294
26,46934,houses,8,2,20640,11032,5.234241e-22,0.251367,NaN,0.846846,...,NaN,NaN,NaN,NaN,0.824988,NaN,NaN,NaN,NaN,NaN
27,46935,HR_Analytics_Job_Change_of_Data_Scientists,12,6,19084,1004,5.308890e-10,0.106718,relevent_experience,NaN,...,0.589422,NaN,0.731788,0.463576,NaN,0.793145,0.586291,NaN,0.741722,0.483444
28,46937,in_vehicle_coupon_recommendation,24,9,12587,178,1.445597e-11,0.154514,expiration,NaN,...,0.521808,NaN,0.518519,0.037037,NaN,0.740147,0.480294,NaN,0.444444,-0.111111
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.756286,NaN,0.917910,0.835821,NaN,0.882012,0.764023,NaN,0.917910,0.835821
30,46939,kddcup09_appetency,212,9,50000,27,0.000000e+00,0.105469,Var116,NaN,...,0.961600,NaN,NaN,NaN,NaN,0.980800,0.961600,NaN,NaN,NaN
31,46940,Marketing_Campaign,25,8,2039,67,3.460081e-32,0.116319,AcceptedCmp3,NaN,...,0.773810,NaN,0.571429,0.142857,NaN,0.888393,0.776786,NaN,0.571429,0.142857
32,46941,maternal_health_risk,6,2,416,40,7.372958e-06,0.312500,NaN,NaN,...,0.665574,NaN,NaN,NaN,NaN,0.688525,0.532787,NaN,NaN,NaN
33,46942,miami_housing,15,4,13776,2812,1.011417e-44,0.244097,avno60plus,0.925494,...,NaN,0.321257,NaN,NaN,0.911543,NaN,NaN,0.260518,NaN,NaN
34,46980,MIC,111,6,1699,52,1.038332e-68,0.106996,SEX,NaN,...,0.865546,NaN,0.875000,0.857143,NaN,0.868627,0.849860,NaN,0.875000,0.857143
35,46969,NATICUSdroid,86,9,7395,52,9.557813e-23,0.101562,com.android.launcher.permission.UNINSTALL_SHOR...,NaN,...,0.886121,NaN,0.812500,0.625000,NaN,0.943060,0.886121,NaN,0.812500,0.625000
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.792917,NaN,0.858407,0.716814,NaN,0.889159,0.778318,NaN,0.884956,0.769912
37,46949,physiochemical_protein,9,1,43974,341,4.142389e-35,1.000000,NaN,0.644327,...,NaN,NaN,NaN,NaN,0.579676,NaN,NaN,NaN,NaN,NaN
38,46950,polish_companies_bankruptcy,64,1,5850,3255,9.503573e-236,1.000307,NaN,NaN,...,0.922166,NaN,NaN,NaN,NaN,0.950931,0.901861,NaN,NaN,NaN
39,46952,qsar-biodeg,41,5,1051,15,2.447264e-63,0.156250,Presence_CBr_At_Dist1,NaN,...,0.716088,NaN,NaN,NaN,NaN,0.813880,0.627760,NaN,NaN,NaN
40,46953,QSAR-TID-11,1024,9,5259,60,2.925416e-305,0.117188,FCFP6_1024_1015,0.747177,...,NaN,-0.074484,NaN,NaN,0.748240,NaN,NaN,-0.340889,NaN,NaN
41,46954,QSAR_fish_toxicity,6,2,774,23,7.633914e-10,0.657143,NaN,0.465542,...,NaN,NaN,NaN,NaN,0.524539,NaN,NaN,NaN,NaN,NaN
42,46955,SDSS17,11,2,78053,6000,2.075436e-42,1.000000,NaN,NaN,...,0.967458,NaN,NaN,NaN,NaN,0.971686,0.957529,NaN,NaN,NaN
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.840206,NaN,0.937500,0.875000,NaN,0.920103,0.840206,NaN,0.937500,0.875000
44,46958,splice,60,7,3005,2554,6.838044e-38,0.155884,NaN,NaN,...,0.949843,NaN,0.582790,0.374185,NaN,0.935214,0.902821,NaN,0.585398,0.378096
45,46960,students_dropout_and_academic_success,36,9,4424,175,1.290519e-40,0.113932,Daytimeevening_attendance,NaN,...,0.662274,NaN,0.566038,0.349057,NaN,0.742470,0.613705,NaN,0.528302,0.292453
46,46961,superconductivity,81,2,15170,45,3.872284e-287,0.714286,NaN,0.917708,...,NaN,NaN,NaN,NaN,0.898582,NaN,NaN,NaN,NaN,NaN
47,46962,taiwanese_bankruptcy_prediction,94,2,6819,389,0.000000e+00,0.510499,Liability_Assets_Flag,NaN,...,0.938416,NaN,NaN,NaN,NaN,0.968719,0.937439,NaN,NaN,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.822660,NaN,0.773810,0.660714,NaN,0.862069,0.793103,NaN,0.767857,0.651786
49,46964,wine_quality,12,3,5320,2368,4.506093e-22,0.125503,wine_color,0.449589,...,NaN,0.070603,NaN,NaN,0.320265,NaN,NaN,0.043394,NaN,NaN
50,46979,jm1,21,2,8824,227,3.679058e-50,0.137576,NaN,NaN,...,0.627067,NaN,NaN,NaN,NaN,0.814758,0.629516,NaN,NaN,NaN

In [3]:
# function to get density information and plot for a specific dataset
def get_density(dataset_id, final_table, all_densities, show_plot=False):
    dataset = final_table[final_table['dataset_id'] == dataset_id]
    densities = all_densities.get(str(dataset_id))

    print("Total features:", dataset['original_number_features'].iloc[0], ", Total rows:", dataset['original_number_rows'].iloc[0])
    print("Original density:", dataset['original_density'].iloc[0])
    #print()
    print("Features left:", dataset['final_number_features'].iloc[0], ", Rows left:", dataset['final_number_rows'].iloc[0])
    print("Final density:", dataset['final_density'].iloc[0])
    print()

    if show_plot:
        fig = px.line(
                x=range(0, len(densities), 1),
                y=densities,
                labels={"x": "Number features dropped", "y": "Density"},
            )
        fig.show()

In [4]:
# iterate over TabArena datasets and get density plots
tabArenaURL = 'https://raw.githubusercontent.com/TabArena/tabarena_dataset_curation/refs/heads/main/dataset_creation_scripts/metadata/tabarena_dataset_metadata.csv'
iterator = TabArenaIterator(tabArenaURL)

for row, df in iterator:
    dataset_id = row['dataset_id']
    print('dataset_id:', dataset_id)

    get_density(dataset_id, final_table, all_densities, show_plot=True)

dataset_id: 46904
Total features: 5 , Total rows: 1503
Original density: 0.0010519022423784
Features left: 4 , Rows left: 1503
Final density: 0.1104497354497354

dataset_id: 46905
Total features: 9 , Total rows: 32769
Original density: 5.4331464888837344e-21
Features left: 1 , Rows left: 67
Final density: 1.0

dataset_id: 46906
Total features: 38 , Total rows: 886
Original density: 6.763894527119904e-16
Features left: 13 , Rows left: 9
Final density: 0.140625

dataset_id: 46907
Total features: 7 , Total rows: 1515
Original density: 5.646737052785582e-10
Features left: 3 , Rows left: 34
Final density: 0.3541666666666667

dataset_id: 46908
Total features: 170 , Total rows: 76000
Original density: 0.0
Features left: 3 , Rows left: 52
Final density: 0.8666666666666667

dataset_id: 46910
Total features: 13 , Total rows: 44905
Original density: 5.349772965830006e-12
Features left: 8 , Rows left: 2533
Final density: 0.1832320601851851

dataset_id: 46911
Total features: 10 , Total rows: 10000
Original density: 4.6085769342056656e-12
Features left: 6 , Rows left: 723
Final density: 0.6846590909090909

dataset_id: 46912
Total features: 1776 , Total rows: 3751
Original density: 0.0
Features left: 9 , Rows left: 87
Final density: 0.169921875

dataset_id: 46913
Total features: 4 , Total rows: 502
Original density: 0.0001906424193814
Features left: 2 , Rows left: 188
Final density: 0.1837732160312805

dataset_id: 46915
Total features: 19 , Total rows: 5000
Original density: 2.774980106523841e-36
Features left: 5 , Rows left: 625
Final density: 0.248015873015873

dataset_id: 46916
Total features: 85 , Total rows: 8261
Original density: 4.188386241439141e-67
Features left: 6 , Rows left: 17
Final density: 0.1770833333333333

dataset_id: 46917
Total features: 8 , Total rows: 996
Original density: 3.038551332339308e-15
Features left: 2 , Rows left: 452
Final density: 0.208294930875576

dataset_id: 46918
Total features: 20 , Total rows: 1000
Original density: 1.4033527721394344e-13
Features left: 7 , Rows left: 128
Final density: 0.1481481481481481

dataset_id: 46919
Total features: 23 , Total rows: 29944
Original density: 4.9283839727975495e-57
Features left: 4 , Rows left: 201
Final density: 0.3589285714285714

dataset_id: 46920
Total features: 21 , Total rows: 129880
Original density: 1.8612414495883584e-18
Features left: 8 , Rows left: 16181
Final density: 0.2080889917695473

dataset_id: 46921
Total features: 8 , Total rows: 768
Original density: 1.11749823141236e-13
Features left: 2 , Rows left: 283
Final density: 0.3541927409261577

dataset_id: 46922
Total features: 47 , Total rows: 71518
Original density: 7.57843832073672e-37
Features left: 9 , Rows left: 9
Final density: 0.140625

dataset_id: 46923
Total features: 9 , Total rows: 53595
Original density: 2.616386759811203e-13
Features left: 3 , Rows left: 276
Final density: 0.9857142857142858

dataset_id: 46924
Total features: 10 , Total rows: 10999
Original density: 9.03257841376853e-09
Features left: 7 , Rows left: 4761
Final density: 0.2204166666666666

dataset_id: 46927
Total features: 6 , Total rows: 1499
Original density: 1.051149451208826e-05
Features left: 4 , Rows left: 176
Final density: 0.1102756892230576

dataset_id: 46928
Total features: 9 , Total rows: 45242
Original density: 5.407391379869e-16
Features left: 4 , Rows left: 3221
Final density: 0.3268060064935065

dataset_id: 46929
Total features: 10 , Total rows: 149354
Original density: 1.066472191353621e-19
Features left: 3 , Rows left: 323
Final density: 0.1194526627218934

dataset_id: 46930
Total features: 30 , Total rows: 2400
Original density: 4.281293536606587e-90
Features left: 1 , Rows left: 781
Final density: 1.0

dataset_id: 46931
Total features: 6 , Total rows: 1335
Original density: 0.0005399227364497
Features left: 5 , Rows left: 986
Final density: 0.2185283687943262

dataset_id: 46932
Total features: 23 , Total rows: 9871
Original density: 1.4832573002592818e-35
Features left: 3 , Rows left: 184
Final density: 0.1352941176470588

dataset_id: 46933
Total features: 1617 , Total rows: 3825
Original density: 0.0
Features left: 9 , Rows left: 55
Final density: 0.107421875

dataset_id: 46934
Total features: 8 , Total rows: 20640
Original density: 5.234241194407872e-22
Features left: 2 , Rows left: 11032
Final density: 0.2513671162960262

dataset_id: 46935
Total features: 12 , Total rows: 19084
Original density: 5.30889048214203e-10
Features left: 6 , Rows left: 1004
Final density: 0.1067176870748299

dataset_id: 46937
Total features: 24 , Total rows: 12587
Original density: 1.445596993304525e-11
Features left: 9 , Rows left: 178
Final density: 0.1545138888888889

dataset_id: 46938
Total features: 13 , Total rows: 1723
Original density: 1.3356526487161814e-10
Features left: 7 , Rows left: 444
Final density: 0.2055555555555555

dataset_id: 46939
Total features: 212 , Total rows: 50000
Original density: 0.0
Features left: 9 , Rows left: 27
Final density: 0.10546875

dataset_id: 46940
Total features: 25 , Total rows: 2039
Original density: 3.46008068054626e-32
Features left: 8 , Rows left: 67
Final density: 0.1163194444444444

dataset_id: 46941
Total features: 6 , Total rows: 416
Original density: 7.372958257713248e-06
Features left: 2 , Rows left: 40
Final density: 0.3125

dataset_id: 46942
Total features: 15 , Total rows: 13776
Original density: 1.011417240408681e-44
Features left: 4 , Rows left: 2812
Final density: 0.2440972222222222

dataset_id: 46980
Total features: 111 , Total rows: 1699
Original density: 1.038332178849761e-68
Features left: 6 , Rows left: 52
Final density: 0.1069958847736625

dataset_id: 46969
Total features: 86 , Total rows: 7395
Original density: 9.557813484108812e-23
Features left: 9 , Rows left: 52
Final density: 0.1015625

dataset_id: 46947
Total features: 17 , Total rows: 12205
Original density: 1.3093726543475288e-29
Features left: 5 , Rows left: 374
Final density: 0.1442901234567901

dataset_id: 46949
Total features: 9 , Total rows: 43974
Original density: 4.1423888331511546e-35
Features left: 1 , Rows left: 341
Final density: 1.0

dataset_id: 46950
Total features: 64 , Total rows: 5850
Original density: 9.503573095074775e-236
Features left: 1 , Rows left: 3255
Final density: 1.0003073140749847

dataset_id: 46952
Total features: 41 , Total rows: 1051
Original density: 2.447263710241777e-63
Features left: 5 , Rows left: 15
Final density: 0.15625

dataset_id: 46953
Total features: 1024 , Total rows: 5259
Original density: 2.925415855472343e-305
Features left: 9 , Rows left: 60
Final density: 0.1171875

dataset_id: 46954
Total features: 6 , Total rows: 774
Original density: 7.633914023940202e-10
Features left: 2 , Rows left: 23
Final density: 0.6571428571428571

dataset_id: 46955
Total features: 11 , Total rows: 78053
Original density: 2.0754355569286492e-42
Features left: 2 , Rows left: 6000
Final density: 1.0

dataset_id: 46956
Total features: 15 , Total rows: 2578
Original density: 9.400295346125564e-18
Features left: 6 , Rows left: 53
Final density: 0.1840277777777778

dataset_id: 46958
Total features: 60 , Total rows: 3005
Original density: 6.838044444444444e-38
Features left: 7 , Rows left: 2554
Final density: 0.1558837890625

dataset_id: 46960
Total features: 36 , Total rows: 4424
Original density: 1.2905192552173215e-40
Features left: 9 , Rows left: 175
Final density: 0.1139322916666666

dataset_id: 46961
Total features: 81 , Total rows: 15170
Original density: 3.872284267669358e-287
Features left: 2 , Rows left: 45
Final density: 0.7142857142857143

dataset_id: 46962
Total features: 94 , Total rows: 6819
Original density: 0.0
Features left: 2 , Rows left: 389
Final density: 0.510498687664042

dataset_id: 46963
Total features: 9 , Total rows: 676
Original density: 0.0772748056698674
Features left: 8 , Rows left: 558
Final density: 0.191358024691358

dataset_id: 46964
Total features: 12 , Total rows: 5320
Original density: 4.506093482946806e-22
Features left: 3 , Rows left: 2368
Final density: 0.125503497986008

dataset_id: 46979
Total features: 21 , Total rows: 8824
Original density: 3.679058450207553e-50
Features left: 2 , Rows left: 227
Final density: 0.1375757575757575

# Analysis of results

In [5]:
# calculate improvement columns
def calculateInitialFinalImprovement(x):
    if pd.notna(x.initial_XGB_r2):
        return (x.final_XGB_r2 - x.initial_XGB_r2)/abs(x.initial_XGB_r2) * 100
    else:
        return (x.final_XGB_normalized_accuracy - x.initial_XGB_normalized_accuracy)/abs(x.initial_XGB_normalized_accuracy) * 100 
final_table['final_improvement_xgb'] = final_table.apply(lambda x : calculateInitialFinalImprovement(x), axis=1)
final_table['final_improvement_accuracy'] = final_table.apply(lambda x : (x.final_XGB_normalized_accuracy - x.final_NN_TORCH_normalized_accuracy)/x.final_NN_TORCH_normalized_accuracy * 100, axis=1)
final_table['final_improvement_r2'] = final_table.apply(lambda x : (x.final_XGB_r2 - x.final_NN_TORCH_r2)/x.final_NN_TORCH_r2 * 100, axis=1)
final_table

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy,final_improvement_xgb,final_improvement_accuracy,final_improvement_r2
0,46904,airfoil_self_noise,5,4,1503,1503,1.051902e-03,0.110450,NaN,0.950645,...,NaN,0.947991,NaN,NaN,0.928413,NaN,NaN,-2.823931,NaN,-0.496868
1,46905,Amazon_employee_access,9,1,32769,67,5.433146e-21,1.000000,NaN,NaN,...,NaN,NaN,0.944563,0.889126,NaN,NaN,NaN,NaN,NaN,NaN
2,46906,anneal,38,13,886,9,6.763895e-16,0.140625,bf,NaN,...,NaN,NaN,0.992593,0.990741,NaN,NaN,NaN,NaN,NaN,NaN
3,46907,Another-Dataset-on-used-Fiat-500,7,3,1515,34,5.646737e-10,0.354167,NaN,0.830676,...,NaN,0.836072,NaN,NaN,-0.064585,NaN,NaN,-121.716762,NaN,179.316029
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.875000,NaN,0.992325,0.984649,NaN,0.750000,0.500000,-11.120021,75.000000,NaN
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.773684,NaN,0.895827,0.791654,NaN,0.888158,0.776316,-1.388342,-0.338983,NaN
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.603687,NaN,0.847333,0.694667,NaN,0.806452,0.612903,-15.450051,-1.503759,NaN
7,46912,Bioresponse,1776,9,3751,87,0.000000e+00,0.169922,D1736,NaN,...,0.259259,NaN,0.761989,0.523979,NaN,0.629630,0.259259,-52.762795,0.000000,NaN
8,46913,blood-transfusion-service-center,4,2,502,188,1.906424e-04,0.183773,NaN,NaN,...,NaN,NaN,0.733333,0.466667,NaN,NaN,NaN,NaN,NaN,NaN
9,46915,churn,19,5,5000,625,2.774980e-36,0.248016,international_plan,NaN,...,0.542553,NaN,0.918667,0.837333,NaN,0.792553,0.585106,-40.422417,-7.272727,NaN
10,46916,coil2000_insurance_policies,85,6,8261,17,4.188386e-67,0.177083,contributionBicyclePolicies,NaN,...,NaN,NaN,0.933152,0.866305,NaN,NaN,NaN,NaN,NaN,NaN
11,46917,concrete_compressive_strength,8,2,996,452,3.038551e-15,0.208295,NaN,0.867073,...,NaN,0.884803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,46918,credit-g,20,7,1000,128,1.403353e-13,0.148148,people_liable,NaN,...,0.333333,NaN,0.720000,0.440000,NaN,0.717949,0.435897,-29.577465,-23.529412,NaN
13,46919,credit_card_clients_default,23,4,29944,201,4.928384e-57,0.358929,SEX,NaN,...,0.180328,NaN,0.818778,0.637556,NaN,0.688525,0.377049,-71.950383,-52.173913,NaN
14,46920,customer_satisfaction_in_airline,21,8,129880,16181,1.861241e-18,0.208089,CustomerType,NaN,...,0.587230,NaN,0.947105,0.894210,NaN,0.798764,0.597528,-35.456089,-1.723544,NaN
15,46921,diabetes,8,2,768,283,1.117498e-13,0.354193,NaN,NaN,...,NaN,NaN,0.761905,0.523810,NaN,NaN,NaN,NaN,NaN,NaN
16,46922,Diabetes130US,47,9,71518,9,7.578438e-37,0.140625,tolazamide,NaN,...,NaN,NaN,0.914010,0.828020,NaN,NaN,NaN,NaN,NaN,NaN
17,46923,diamonds,9,3,53595,276,2.616387e-13,0.985714,NaN,0.981644,...,NaN,0.977045,NaN,NaN,-0.026704,NaN,NaN,-104.955231,NaN,82.158067
18,46924,E-CommereShippingData,10,7,10999,4761,9.032578e-09,0.220417,Gender,NaN,...,0.184045,NaN,0.670303,0.340606,NaN,0.599020,0.198041,-46.441993,-7.067138,NaN
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.509434,NaN,0.802222,0.604444,NaN,0.811321,0.622642,-3.678453,-18.181818,NaN
20,46928,Food_Delivery_Time,9,4,45242,3221,5.407391e-16,0.326806,NaN,0.376339,...,NaN,0.312180,NaN,NaN,0.461866,NaN,NaN,33.871679,NaN,9.081692
21,46929,GiveMeSomeCredit,10,3,149354,323,1.066472e-19,0.119453,FinancialDistressNextTwoYears,NaN,...,0.319588,NaN,0.934778,0.869556,NaN,0.639175,0.278351,-63.344438,14.814815,NaN
22,46930,hazelnut-spread-contaminant-detection,30,1,2400,781,4.281294e-90,1.000000,NaN,NaN,...,NaN,NaN,0.931944,0.863889,NaN,NaN,NaN,NaN,NaN,NaN
23,46931,healthcare_insurance_expenses,6,5,1335,986,5.399227e-04,0.218528,sex,0.806058,...,NaN,0.803626,NaN,NaN,0.610852,NaN,NaN,-23.770220,NaN,0.590048
24,46932,heloc,23,3,9871,184,1.483257e-35,0.135294,RiskPerformance,NaN,...,0.428571,NaN,0.715424,0.430848,NaN,0.714286,0.428571,-5.690242,0.000000,NaN
25,46933,hiva_agnostic,1617,9,3825,55,0.000000e+00,0.107422,molecule_structure_property_1609,NaN,...,0.735294,NaN,0.962738,0.944107,NaN,0.823529,0.735294,-22.117539,0.000000,NaN
26,46934,houses,8,2,20640,11032,5.234241e-22,0.251367,NaN,0.846846,...,NaN,0.824988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,46935,HR_Analytics_Job_Change_of_Data_Scientists,12,6,19084,1004,5.308890e-10,0.106718,relevent_experience,NaN,...,0.463576,NaN,0.793145,0.586291,NaN,0.741722,0.483444,-21.350774,-4.109589,NaN
28,46937,in_vehicle_coupon_recommendation,24,9,12587,178,1.445597e-11,0.154514,expiration,NaN,...,0.037037,NaN,0.740147,0.480294,NaN,0.444444,-0.111111,-92.902167,-133.333333,NaN
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.835821,NaN,0.882012,0.764023,NaN,0.917910,0.835821,10.516471,0.000000,NaN
30,46939,kddcup09_appetency,212,9,50000,27,0.000000e+00,0.105469,Var116,NaN,...,NaN,NaN,0.980800,0.961600,NaN,NaN,NaN,NaN,NaN,NaN
31,46940,Marketing_Campaign,25,8,2039,67,3.460081e-32,0.116319,AcceptedCmp3,NaN,...,0.142857,NaN,0.888393,0.776786,NaN,0.571429,0.142857,-81.538462,0.000000,NaN
32,46941,maternal_health_risk,6,2,416,40,7.372958e-06,0.312500,NaN,NaN,...,NaN,NaN,0.688525,0.532787,NaN,NaN,NaN,NaN,NaN,NaN
33,46942,miami_housing,15,4,13776,2812,1.011417e-44,0.244097,avno60plus,0.925494,...,NaN,0.911543,NaN,NaN,0.260518,NaN,NaN,-65.288075,NaN,23.314649
34,46980,MIC,111,6,1699,52,1.038332e-68,0.106996,SEX,NaN,...,0.857143,NaN,0.868627,0.849860,NaN,0.875000,0.857143,-0.970874,0.000000,NaN
35,46969,NATICUSdroid,86,9,7395,52,9.557813e-23,0.101562,com.android.launcher.permission.UNINSTALL_SHOR...,NaN,...,0.625000,NaN,0.943060,0.886121,NaN,0.812500,0.625000,-29.467871,0.000000,NaN
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.716814,NaN,0.889159,0.778318,NaN,0.884956,0.769912,-9.597832,-6.896552,NaN
37,46949,physiochemical_protein,9,1,43974,341,4.142389e-35,1.000000,NaN,0.644327,...,NaN,0.579676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,46950,polish_companies_bankruptcy,64,1,5850,3255,9.503573e-236,1.000307,NaN,NaN,...,NaN,NaN,0.950931,0.901861,NaN,NaN,NaN,NaN,NaN,NaN
39,46952,qsar-biodeg,41,5,1051,15,2.447264e-63,0.156250,Presence_CBr_At_Dist1,NaN,...,NaN,NaN,0.813880,0.627760,NaN,NaN,NaN,NaN,NaN,NaN
40,46953,QSAR-TID-11,1024,9,5259,60,2.925416e-305,0.117188,FCFP6_1024_1015,0.747177,...,NaN,0.748240,NaN,NaN,-0.340889,NaN,NaN,-109.968775,NaN,-78.149971
41,46954,QSAR_fish_toxicity,6,2,774,23,7.633914e-10,0.657143,NaN,0.465542,...,NaN,0.524539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,46955,SDSS17,11,2,78053,6000,2.075436e-42,1.000000,NaN,NaN,...,NaN,NaN,0.971686,0.957529,NaN,NaN,NaN,NaN,NaN,NaN
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.875000,NaN,0.920103,0.840206,NaN,0.937500,0.875000,4.141104,0.000000,NaN
44,46958,splice,60,7,3005,2554,6.838044e-38,0.155884,NaN,NaN,...,0.374185,NaN,0.935214,0.902821,NaN,0.585398,0.378096,-60.605591,-1.034483,NaN
45,46960,students_dropout_and_academic_success,36,9,4424,175,1.290519e-40,0.113932,Daytimeevening_attendance,NaN,...,0.349057,NaN,0.742470,0.613705,NaN,0.528302,0.292453,-47.294239,19.354839,NaN
46,46961,superconductivity,81,2,15170,45,3.872284e-287,0.714286,NaN,0.917708,...,NaN,0.898582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,46962,taiwanese_bankruptcy_prediction,94,2,6819,389,0.000000e+00,0.510499,Liability_Assets_Flag,NaN,...,NaN,NaN,0.968719,0.937439,NaN,NaN,NaN,NaN,NaN,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.660714,NaN,0.862069,0.793103,NaN,0.767857,0.651786,-19.685629,1.369863,NaN
49,46964,wine_quality,12,3,5320,2368,4.506093e-22,0.125503,wine_color,0.449589,...,NaN,0.320265,NaN,NaN,0.043394,NaN,NaN,-84.296099,NaN,62.702585
50,46979,jm1,21,2,8824,227,3.679058e-50,0.137576,NaN,NaN,...,NaN,NaN,0.814758,0.629516,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# filter datasets with at least 3 features and 30 rows after density improvement process
final_table_filtered = final_table[(final_table['final_number_features'] >= 3) & (final_table['final_number_rows'] >= 30)]
final_table_filtered

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy,final_improvement_xgb,final_improvement_accuracy,final_improvement_r2
0,46904,airfoil_self_noise,5,4,1503,1503,1.051902e-03,0.110450,NaN,0.950645,...,NaN,0.947991,NaN,NaN,0.928413,NaN,NaN,-2.823931,NaN,-0.496868
3,46907,Another-Dataset-on-used-Fiat-500,7,3,1515,34,5.646737e-10,0.354167,NaN,0.830676,...,NaN,0.836072,NaN,NaN,-0.064585,NaN,NaN,-121.716762,NaN,179.316029
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.875000,NaN,0.992325,0.984649,NaN,0.750000,0.500000,-11.120021,75.000000,NaN
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.773684,NaN,0.895827,0.791654,NaN,0.888158,0.776316,-1.388342,-0.338983,NaN
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.603687,NaN,0.847333,0.694667,NaN,0.806452,0.612903,-15.450051,-1.503759,NaN
7,46912,Bioresponse,1776,9,3751,87,0.000000e+00,0.169922,D1736,NaN,...,0.259259,NaN,0.761989,0.523979,NaN,0.629630,0.259259,-52.762795,0.000000,NaN
9,46915,churn,19,5,5000,625,2.774980e-36,0.248016,international_plan,NaN,...,0.542553,NaN,0.918667,0.837333,NaN,0.792553,0.585106,-40.422417,-7.272727,NaN
12,46918,credit-g,20,7,1000,128,1.403353e-13,0.148148,people_liable,NaN,...,0.333333,NaN,0.720000,0.440000,NaN,0.717949,0.435897,-29.577465,-23.529412,NaN
13,46919,credit_card_clients_default,23,4,29944,201,4.928384e-57,0.358929,SEX,NaN,...,0.180328,NaN,0.818778,0.637556,NaN,0.688525,0.377049,-71.950383,-52.173913,NaN
14,46920,customer_satisfaction_in_airline,21,8,129880,16181,1.861241e-18,0.208089,CustomerType,NaN,...,0.587230,NaN,0.947105,0.894210,NaN,0.798764,0.597528,-35.456089,-1.723544,NaN
17,46923,diamonds,9,3,53595,276,2.616387e-13,0.985714,NaN,0.981644,...,NaN,0.977045,NaN,NaN,-0.026704,NaN,NaN,-104.955231,NaN,82.158067
18,46924,E-CommereShippingData,10,7,10999,4761,9.032578e-09,0.220417,Gender,NaN,...,0.184045,NaN,0.670303,0.340606,NaN,0.599020,0.198041,-46.441993,-7.067138,NaN
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.509434,NaN,0.802222,0.604444,NaN,0.811321,0.622642,-3.678453,-18.181818,NaN
20,46928,Food_Delivery_Time,9,4,45242,3221,5.407391e-16,0.326806,NaN,0.376339,...,NaN,0.312180,NaN,NaN,0.461866,NaN,NaN,33.871679,NaN,9.081692
21,46929,GiveMeSomeCredit,10,3,149354,323,1.066472e-19,0.119453,FinancialDistressNextTwoYears,NaN,...,0.319588,NaN,0.934778,0.869556,NaN,0.639175,0.278351,-63.344438,14.814815,NaN
23,46931,healthcare_insurance_expenses,6,5,1335,986,5.399227e-04,0.218528,sex,0.806058,...,NaN,0.803626,NaN,NaN,0.610852,NaN,NaN,-23.770220,NaN,0.590048
24,46932,heloc,23,3,9871,184,1.483257e-35,0.135294,RiskPerformance,NaN,...,0.428571,NaN,0.715424,0.430848,NaN,0.714286,0.428571,-5.690242,0.000000,NaN
25,46933,hiva_agnostic,1617,9,3825,55,0.000000e+00,0.107422,molecule_structure_property_1609,NaN,...,0.735294,NaN,0.962738,0.944107,NaN,0.823529,0.735294,-22.117539,0.000000,NaN
27,46935,HR_Analytics_Job_Change_of_Data_Scientists,12,6,19084,1004,5.308890e-10,0.106718,relevent_experience,NaN,...,0.463576,NaN,0.793145,0.586291,NaN,0.741722,0.483444,-21.350774,-4.109589,NaN
28,46937,in_vehicle_coupon_recommendation,24,9,12587,178,1.445597e-11,0.154514,expiration,NaN,...,0.037037,NaN,0.740147,0.480294,NaN,0.444444,-0.111111,-92.902167,-133.333333,NaN
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.835821,NaN,0.882012,0.764023,NaN,0.917910,0.835821,10.516471,0.000000,NaN
31,46940,Marketing_Campaign,25,8,2039,67,3.460081e-32,0.116319,AcceptedCmp3,NaN,...,0.142857,NaN,0.888393,0.776786,NaN,0.571429,0.142857,-81.538462,0.000000,NaN
33,46942,miami_housing,15,4,13776,2812,1.011417e-44,0.244097,avno60plus,0.925494,...,NaN,0.911543,NaN,NaN,0.260518,NaN,NaN,-65.288075,NaN,23.314649
34,46980,MIC,111,6,1699,52,1.038332e-68,0.106996,SEX,NaN,...,0.857143,NaN,0.868627,0.849860,NaN,0.875000,0.857143,-0.970874,0.000000,NaN
35,46969,NATICUSdroid,86,9,7395,52,9.557813e-23,0.101562,com.android.launcher.permission.UNINSTALL_SHOR...,NaN,...,0.625000,NaN,0.943060,0.886121,NaN,0.812500,0.625000,-29.467871,0.000000,NaN
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.716814,NaN,0.889159,0.778318,NaN,0.884956,0.769912,-9.597832,-6.896552,NaN
40,46953,QSAR-TID-11,1024,9,5259,60,2.925416e-305,0.117188,FCFP6_1024_1015,0.747177,...,NaN,0.748240,NaN,NaN,-0.340889,NaN,NaN,-109.968775,NaN,-78.149971
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.875000,NaN,0.920103,0.840206,NaN,0.937500,0.875000,4.141104,0.000000,NaN
44,46958,splice,60,7,3005,2554,6.838044e-38,0.155884,NaN,NaN,...,0.374185,NaN,0.935214,0.902821,NaN,0.585398,0.378096,-60.605591,-1.034483,NaN
45,46960,students_dropout_and_academic_success,36,9,4424,175,1.290519e-40,0.113932,Daytimeevening_attendance,NaN,...,0.349057,NaN,0.742470,0.613705,NaN,0.528302,0.292453,-47.294239,19.354839,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.660714,NaN,0.862069,0.793103,NaN,0.767857,0.651786,-19.685629,1.369863,NaN
49,46964,wine_quality,12,3,5320,2368,4.506093e-22,0.125503,wine_color,0.449589,...,NaN,0.320265,NaN,NaN,0.043394,NaN,NaN,-84.296099,NaN,62.702585

In [7]:
# get histogram comparing original_density and final_density
fig = go.Figure()

fig.add_trace(go.Histogram(x=final_table['final_density'], name="Final_density", texttemplate="%{y}"))
fig.add_trace(go.Histogram(x=final_table['original_density'], name="Original_density", texttemplate="%{y}"))

# The two histograms are drawn on top of another
fig.update_layout(barmode='stack', bargap=0.1)
fig.update_layout(
    title='Comparison of Original vs Final Density',
        xaxis=dict(
            title=dict(
                text="Density"
            )
        ),
        yaxis=dict(
            title=dict(
                text="Count"
            )
        )
)
fig.show()

In [8]:
# get box plots comparing initial and final model performances
fig = go.Figure()
fig.add_trace(go.Box(y=final_table['initial_XGB_normalized_accuracy'], name='initial_XGB_normalized_accuracy', boxmean=True))
fig.add_trace(go.Box(y=final_table['final_XGB_normalized_accuracy'], name='final_XGB_normalized_accuracy', boxmean=True))
fig.add_trace(go.Box(y=final_table['initial_NN_TORCH_normalized_accuracy'], name = 'initial_NN_TORCH_normalized_accuracy', boxmean=True))
fig.add_trace(go.Box(y=final_table['final_NN_TORCH_normalized_accuracy'], name = 'final_NN_TORCH_normalized_accuracy', boxmean=True))

fig.add_trace(go.Box(y=final_table['initial_XGB_r2'], name='initial_XGB_r2', boxmean=True))
fig.add_trace(go.Box(y=final_table['final_XGB_r2'], name='final_XGB_r2', boxmean=True))
fig.add_trace(go.Box(y=final_table['initial_NN_TORCH_r2'], name = 'initial_NN_TORCH_r2', boxmean=True))
fig.add_trace(go.Box(y=final_table['final_NN_TORCH_r2'], name = 'final_NN_TORCH_r2', boxmean=True))

fig.update_layout(title='Comparison of Initial vs Final Model Performances')
fig.show()

In [9]:
# check datasets where at least one model has final normalized accuracy > 0.6
final_table[(final_table['final_XGB_normalized_accuracy'] > 0.6) | (final_table['final_NN_TORCH_normalized_accuracy'] > 0.6)]

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy,final_improvement_xgb,final_improvement_accuracy,final_improvement_r2
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.875000,NaN,0.992325,0.984649,NaN,0.750000,0.500000,-11.120021,75.000000,NaN
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.773684,NaN,0.895827,0.791654,NaN,0.888158,0.776316,-1.388342,-0.338983,NaN
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.603687,NaN,0.847333,0.694667,NaN,0.806452,0.612903,-15.450051,-1.503759,NaN
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.509434,NaN,0.802222,0.604444,NaN,0.811321,0.622642,-3.678453,-18.181818,NaN
25,46933,hiva_agnostic,1617,9,3825,55,0.000000e+00,0.107422,molecule_structure_property_1609,NaN,...,0.735294,NaN,0.962738,0.944107,NaN,0.823529,0.735294,-22.117539,0.000000,NaN
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.835821,NaN,0.882012,0.764023,NaN,0.917910,0.835821,10.516471,0.000000,NaN
34,46980,MIC,111,6,1699,52,1.038332e-68,0.106996,SEX,NaN,...,0.857143,NaN,0.868627,0.849860,NaN,0.875000,0.857143,-0.970874,0.000000,NaN
35,46969,NATICUSdroid,86,9,7395,52,9.557813e-23,0.101562,com.android.launcher.permission.UNINSTALL_SHOR...,NaN,...,0.625000,NaN,0.943060,0.886121,NaN,0.812500,0.625000,-29.467871,0.000000,NaN
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.716814,NaN,0.889159,0.778318,NaN,0.884956,0.769912,-9.597832,-6.896552,NaN
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.875000,NaN,0.920103,0.840206,NaN,0.937500,0.875000,4.141104,0.000000,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.660714,NaN,0.862069,0.793103,NaN,0.767857,0.651786,-19.685629,1.369863,NaN

In [10]:
# check datasets where at least one model has final r2 > 0.6
final_table[(final_table['final_XGB_r2'] > 0.6) | (final_table['final_NN_TORCH_r2'] > 0.6)]

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy,final_improvement_xgb,final_improvement_accuracy,final_improvement_r2
0,46904,airfoil_self_noise,5,4,1503,1503,0.001052,0.110450,NaN,0.950645,...,NaN,0.947991,NaN,NaN,0.928413,NaN,NaN,-2.823931,NaN,-0.496868
23,46931,healthcare_insurance_expenses,6,5,1335,986,0.000540,0.218528,sex,0.806058,...,NaN,0.803626,NaN,NaN,0.610852,NaN,NaN,-23.770220,NaN,0.590048

In [11]:
# scatter plot of final_density vs improvement in normalized accuracy
fig = px.scatter(final_table, x='final_density', y='final_improvement_accuracy')
fig.update_layout(
        xaxis=dict(
            title=dict(
                text="Final Density"
            )
        ),
        yaxis=dict(
            title=dict(
                text="Improvement in Normalized Accuracy (%)"
            )
        )
)
fig.update_layout(title='Final_density vs improvement in normalized accuracy')
fig.show()

In [12]:
import plotly.express as px
fig = px.scatter(final_table, x='final_density', y='final_improvement_r2')
fig.update_layout(
        xaxis=dict(
            title=dict(
                text="Final Density"
            )
        ),
        yaxis=dict(
            title=dict(
                text="Improvement in R2 (%)"
            )
        )
)
fig.update_layout(title='Final_density vs improvement in R2')
fig.show()