In [10]:
import openml
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
import json

import sys
from pathlib import Path

# Add parent directory to sys.path
sys.path.append(str(Path().resolve().parent))

In [93]:


df_openml = openml.datasets.list_datasets(output_format='dataframe')
df_openml

,did,name,version,uploader,status,format,MajorityClassSize,MaxNominalAttDistinctValues,MinorityClassSize,NumberOfClasses,NumberOfFeatures,NumberOfInstances,NumberOfInstancesWithMissingValues,NumberOfMissingValues,NumberOfNumericFeatures,NumberOfSymbolicFeatures
2,2,anneal,1,1,active,ARFF,684.0,7.0,8.0,5.0,39.0,898.0,898.0,22175.0,6.0,33.0
3,3,kr-vs-kp,1,1,active,ARFF,1669.0,3.0,1527.0,2.0,37.0,3196.0,0.0,0.0,0.0,37.0
4,4,labor,1,1,active,ARFF,37.0,3.0,20.0,2.0,17.0,57.0,56.0,326.0,8.0,9.0
5,5,arrhythmia,1,1,active,ARFF,245.0,13.0,2.0,13.0,280.0,452.0,384.0,408.0,206.0,74.0
6,6,letter,1,1,active,ARFF,813.0,26.0,734.0,26.0,17.0,20000.0,0.0,0.0,16.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47055,47055,project3,1,52595,active,arff,NaN,NaN,NaN,0.0,16.0,437.0,0.0,0.0,16.0,0.0
47056,47056,project3_cat,1,52595,active,arff,NaN,NaN,NaN,0.0,18.0,437.0,266.0,307.0,16.0,0.0
47057,47057,project3_cat_new,1,52595,active,arff,NaN,NaN,NaN,0.0,18.0,437.0,0.0,0.0,18.0,0.0
47058,47058,sail,2,52634,active,arff,NaN,NaN,NaN,NaN,7.0,1239.0,0.0,0.0,5.0,0.0
47059,47059,Division_Non_Restoring,1,51972,active,arff,NaN,NaN,NaN,NaN,8.0,11211.0,11211.0,11211.0,7.0,0.0

In [15]:
dataset = openml.datasets.get_dataset(46904)
# Get the data itself as a dataframe (or otherwise)
X, y, categorical_indicator, attribute_names = dataset.get_data(dataset_format="dataframe")
X

,frequency,attack-angle,chord-length,free-stream-velocity,suction-side-displacement-thickness,scaled-sound-pressure
0,8000,1.5,0.3048,71.3,0.003367,115.372
1,4000,0.0,0.0254,55.5,0.000412,133.223
2,2000,12.3,0.1016,55.5,0.036823,118.564
3,1600,5.3,0.2286,71.3,0.005194,130.460
4,12500,0.0,0.0508,71.3,0.000740,125.220
...,...,...,...,...,...,...
1498,2000,0.0,0.3048,71.3,0.002663,127.461
1499,2000,2.0,0.2286,39.6,0.003466,122.797
1500,8000,0.0,0.0508,71.3,0.000740,130.890
1501,12500,0.0,0.1016,55.5,0.001320,119.910
1502,10000,0.0,0.0254,39.6,0.000428,133.376

In [247]:
dataset = openml.datasets.get_dataset(46927)
# Get the data itself as a dataframe (or otherwise)
X, y, categorical_indicator, attribute_names = dataset.get_data(dataset_format="dataframe")
display(X)
total = 1
X = X.drop(columns=['attended', 'months_as_member', 'weight', 'days_before']).drop_duplicates()
for i in X.nunique().values:
    total = np.multiply(total, i, dtype=object)
print(total)
print(len(X))
len(X)/total

,months_as_member,weight,days_before,day_of_week,time,category,attended
0,15,65.47,6,Wed,AM,HIIT,Yes
1,18,77.85,8,Thu,AM,Strength,Yes
2,13,67.26,10,Fri,AM,Cycling,No
3,7,86.70,12,Sat,AM,HIIT,No
4,5,135.18,8,Thu,AM,HIIT,No
...,...,...,...,...,...,...,...
1495,15,77.20,10,Fri,AM,Cycling,No
1496,17,85.26,6,Wed,AM,Yoga,No
1497,6,95.66,3,Tue,PM,Cycling,No
1498,13,73.31,12,Sat,PM,Cycling,No
1499,13,73.96,8,Thu,AM,Yoga,No

84
74

0.8809523809523809

In [139]:
obj = {'p1': 2, 'p2': 4}
obj['name'] = 'n1'
obj

{'p1': 2, 'p2': 4, 'name': 'n1'}

In [141]:
df1 = pd.DataFrame(columns= ['p1', 'p2', 'p3', 'name'])
df1.loc[len(df1)] = obj
df1

   p1  p2  p3 name
0   2   4 NaN   n1

In [35]:
df1 = pd.DataFrame(columns= ['p1', 'p2', 'p3', 'name'])
df1['jj'] = None
df1['kk'] = None
df1.loc[len(df1)] = obj
df1

   p1  p2  p3  name  jj  kk
0   2   4 NaN   NaN NaN NaN

In [103]:
dataset = openml.datasets.get_dataset(46904)
# Get the data itself as a dataframe (or otherwise)
X, y, categorical_indicator, attribute_names = dataset.get_data(dataset_format="dataframe")
X
dense_df = getDensitiesPlot(X, 'scaled-sound-pressure', 0.1, show_fig=True)
dense_df

Total features: 5 Total rows: 1503
Original density: 0.0010519022423784328

Features left: 4 Rows left: 1503
Final density: 0.11044973544973545

      frequency attack-angle  chord-length  free-stream-velocity
0          8000          1.5        0.3048                  71.3
1          4000          0.0        0.0254                  55.5
2          2000         12.3        0.1016                  55.5
3          1600          5.3        0.2286                  71.3
4         12500          0.0        0.0508                  71.3
...         ...          ...           ...                   ...
1498       2000          0.0        0.3048                  71.3
1499       2000          2.0        0.2286                  39.6
1500       8000          0.0        0.0508                  71.3
1501      12500          0.0        0.1016                  55.5
1502      10000          0.0        0.0254                  39.6

[1503 rows x 4 columns]

In [106]:
dense_df['scaled-sound-pressure'] = X['scaled-sound-pressure'].iloc[dense_df.index,]
dense_df = dense_df.reset_index(drop=True)
dense_df

,frequency,attack-angle,chord-length,free-stream-velocity,scaled-sound-pressure
0,8000,1.5,0.3048,71.3,115.372
1,4000,0.0,0.0254,55.5,133.223
2,2000,12.3,0.1016,55.5,118.564
3,1600,5.3,0.2286,71.3,130.460
4,12500,0.0,0.0508,71.3,125.220
...,...,...,...,...,...
1498,2000,0.0,0.3048,71.3,127.461
1499,2000,2.0,0.2286,39.6,122.797
1500,8000,0.0,0.0508,71.3,130.890
1501,12500,0.0,0.1016,55.5,119.910
1502,10000,0.0,0.0254,39.6,133.376

In [16]:
train_data = X.iloc[:int(len(X) * 0.7), ]
test_data = X.iloc[int(len(X) * 0.7):, ]
display(train_data)

,frequency,attack-angle,chord-length,free-stream-velocity,suction-side-displacement-thickness,scaled-sound-pressure
0,8000,1.5,0.3048,71.3,0.003367,115.372
1,4000,0.0,0.0254,55.5,0.000412,133.223
2,2000,12.3,0.1016,55.5,0.036823,118.564
3,1600,5.3,0.2286,71.3,0.005194,130.460
4,12500,0.0,0.0508,71.3,0.000740,125.220
...,...,...,...,...,...,...
1047,3150,4.8,0.0254,55.5,0.000873,132.354
1048,12500,0.0,0.0508,55.5,0.000762,125.376
1049,630,12.3,0.1016,39.6,0.040827,121.315
1050,1600,15.6,0.1016,71.3,0.043726,121.528
1051,8000,3.3,0.1016,55.5,0.002211,120.569

In [19]:
from  autogluon.tabular import TabularPredictor

label='scaled-sound-pressure'
predictor = TabularPredictor(label=label, problem_type='regression', path='./test', 
                             eval_metric='r2').fit(train_data, hyperparameters={'NN_TORCH':{}}, fit_weighted_ensemble=False, 
                                                         presets='best', time_limit=60, dynamic_stacking=False)

Preset alias specified: 'best' maps to 'best_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.11.8
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.0.0: Wed Sep 17 21:35:32 PDT 2025; root:xnu-12377.1.9~141/RELEASE_ARM64_T6020
CPU Count:          10
Memory Avail:       14.99 GB / 32.00 GB (46.8%)
Disk Space Avail:   388.44 GB / 460.43 GB (84.4%)
===================================================
Presets specified: ['best']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/yuye/Desktop/Pydantic-models/test"
Train Data Rows:    1052
Train Data Columns: 5
Label Column:       scaled-sound-pressure
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    15345.63 MB
	Train Data (Original)  Memory Usage: 0.03 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('category', []) : 1 | ['attack-angle']
		('float', [])    : 3 | ['chord-length', 'free-stream-velocity', 'suction-side-displacement-thickness']
		('int', [])      : 1 | ['frequency']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['attack-angle']
		('float', [])    : 3 | ['chord-length', 'free-stream-velocity', 'suction-side-displacement-thickness']
		('int', [])      : 1 | ['frequency']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.03 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'r2'
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 39.98s of the 59.98s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	0.9563	 = Validation score   (r2)
	24.99s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 33.52s of the 33.52s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.00%)
	0.9466	 = Validation score   (r2)
	4.74s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 32.82s ... Best model: NeuralNetTorch_BAG_L1 | Estimated inference throughput: 4926.4 rows/s (132 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/yuye/Desktop/Pydantic-models/test")

In [20]:
y_pred = predictor.predict(test_data)
y_pred

1052    125.191628
1053    128.517502
1054    128.645889
1055    125.719498
1056    117.121658
           ...
1498    127.116997
1499    123.072144
1500    131.848892
1501    119.560944
1502    134.000397
Name: scaled-sound-pressure, Length: 451, dtype: float32

In [21]:
predictor = TabularPredictor.load('./test')
predictor.evaluate(test_data)

{'r2': 0.9641781264769623,
 'root_mean_squared_error': np.float64(-1.3005538426994856),
 'mean_squared_error': -1.6914402977603982,
 'mean_absolute_error': -0.8814000973585175,
 'pearsonr': 0.9820071724606373,
 'median_absolute_error': -0.6170397949218795}

In [22]:
predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetTorch_BAG_L1,0.964178,0.956344,r2,0.047013,0.026794,24.990230,0.047013,0.026794,24.990230,1,True,1
1,NeuralNetTorch_BAG_L2,0.955116,0.946636,r2,0.076737,0.060550,29.732934,0.029724,0.033756,4.742704,2,True,2

In [231]:
predictor.leaderboard(test_data)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,XGBoost_BAG_L2,0.855333,0.870143,accuracy,0.134176,0.076535,1.458226,0.058426,0.024969,0.896844,2,True,2
1,XGBoost_BAG_L1,0.851667,0.870857,accuracy,0.075750,0.051566,0.561382,0.075750,0.051566,0.561382,1,True,1

In [255]:
predictor.evaluate(test_data)

{'accuracy': 0.853,
 'balanced_accuracy': np.float64(0.7122805001240027),
 'mcc': 0.5056845799434799,
 'roc_auc': np.float64(0.8584057354434624),
 'f1': 0.5722599418040737,
 'precision': 0.7301980198019802,
 'recall': 0.4704944178628389}

In [241]:
predictor.evaluate(test_data)

{'accuracy': 0.8496666666666667,
 'balanced_accuracy': np.float64(0.7089999737880501),
 'mcc': 0.4947856054525358,
 'roc_auc': np.float64(0.857453367933107),
 'f1': 0.5650916104146577,
 'precision': 0.7146341463414634,
 'recall': 0.46730462519936206}

In [233]:
predictor.model_best

'XGBoost_BAG_L1'

# Density plots

## Iteration of all datasets from TabArena

In [2]:
def getDensitiesPlot(df, target_feature, density_threshold=0.1, show_fig = False):
    # Drop the target column and duplicated rows
    df_copy = df.copy().drop(columns=target_feature).drop_duplicates()
    densities = []

    # Calculate the original dataset informations
    original_number_features = len(df_copy.columns)
    original_number_rows = len(df_copy)
    print('Total features:', original_number_features, 'Total rows:', original_number_rows)

    # Calculate the orignial density
    total = 1
    for i in df_copy.nunique().values:
        total = np.multiply(total, i, dtype=object)
    original_density = len(df_copy)/total
    print('Original density:', original_density)
    print()
    densities.append(original_density)

    # Dropping all available columns one by one until the threshold is chased
    for feature, cardinality in df_copy.nunique().sort_values(ascending=False).items():

        # Drop the corresponding column
        df_copy = df_copy.drop(columns=feature).drop_duplicates()
        
        # Calculate agian the density
        total = 1
        for i in df_copy.nunique().values:
            total = np.multiply(total, i, dtype=object)

        density = len(df_copy)/total
        densities.append(density)

        # Check the requirement to stop dropping columns
        if density > density_threshold:
            break
    
    # Calculate the final dataset informations
    final_number_features = len(df_copy.columns)
    final_number_rows = len(df_copy)
    print('Features left:', final_number_features, 'Rows left:', final_number_rows)
    print('Final density:', density)
    print()

    # Plot the column dropping process
    if show_fig:
        fig = px.line(x=range(0, len(densities), 1), y=densities, labels={'x':'Number features dropped', 'y':'Density'})
        fig.show()

    # Return the final dataset and the change informations 
    return densities, df_copy, {'original_number_features': original_number_features,
                                'original_number_rows' : original_number_rows,
                                'original_density': original_density, 
                                'final_number_features': final_number_features,
                                'final_number_rows': final_number_rows,
                                'final_density': density}

In [3]:
import os 

def trainAutogluonModels(dataset, path, problem_type, target_feature, model_hypers, target_numbers):
    # Split the train (70%) and test (30%) dataset
    train_data, test_data = train_test_split(dataset, test_size=0.3, shuffle=True, random_state=123)
    #train_data = dataset.iloc[:int(len(dataset) * 0.7), ]
    #test_data = dataset.iloc[int(len(dataset) * 0.7):, ]

    # Choose the metric for regression or classification
    if problem_type == 'regression':
        metric = 'r2'
    else:
        metric = 'accuracy' 

    # If the path (the model) already exists, load the model, if not, train the model
    if os.path.isdir(path):
        print('Model already exists. Loading...')
        predictor = TabularPredictor.load(path)
    else:
        print('Train a new model...')
        predictor = TabularPredictor(label=target_feature, path=path, 
                                     eval_metric=metric, problem_type=problem_type,
                                     verbosity=0).fit(train_data, hyperparameters=model_hypers, fit_weighted_ensemble=False, 
                                                      time_limit=60, dynamic_stacking=False,
                                                      presets='medium' #if target_feature == 'LET_IS' else 'best',
                                                      )
    #print(path)
    # Get the metric
    result_metric = predictor.evaluate(test_data).get(metric)

    if metric == 'accuracy':
        chance = 1/target_numbers
        normalized_accuracy = (result_metric - chance)/ (1-chance)
    else:
        normalized_accuracy = None

    return metric, result_metric, normalized_accuracy

In [ ]:
from TabArenaIterator import TabArenaIterator
from autogluon.tabular import TabularPredictor
import os
import pandas as pd
import numpy as np

models= ['XGB', 'NN_TORCH']
all_densities = {}

final_table = pd.DataFrame(columns=['dataset_id', 'dataset_name', 
                                    'original_number_features', 'final_number_features',
                                    'original_number_rows', 'final_number_rows',
                                    'original_density', 'final_density', 'binary_feature'])

# Create the columns for models metrics
for model in models:
    final_table['initial_' + model + '_r2'] = None
    final_table['initial_' + model + '_accuracy'] = None
    final_table['initial_' + model + '_normalized_accuracy'] = None
    final_table['final_' + model + '_r2'] = None
    final_table['final_' + model + '_accuracy'] = None
    final_table['final_' + model + '_normalized_accuracy'] = None

tabArenaURL = 'https://raw.githubusercontent.com/TabArena/tabarena_dataset_curation/refs/heads/main/dataset_creation_scripts/metadata/tabarena_dataset_metadata.csv'
iterator = TabArenaIterator(tabArenaURL)
for row, df in iterator:
    print(row['dataset_id'])

    #if row['dataset_id'] != 46964:
    #    continue

    # Obtain the dense df and informations about the changes
    densities, dense_df, infos = getDensitiesPlot(df, row['target_feature'], density_threshold=0.1, show_fig=False)
    all_densities[str(row['dataset_id'])] = densities

    # Train the initial models and get the metrics
    for model in models:
        metric, result, normalized_accuracy = trainAutogluonModels(df, '../AutoGluonModels/' + 'initial_' + model + '_' + row['dataset_name'], 
                                                        row['problem_type'], row['target_feature'], {model:{}}, row['num_classes'])
        infos['initial_' + model + '_' + metric] = result
        infos['initial_' + model + '_normalized_accuracy'] = normalized_accuracy

    # If the dense df does not fulfill the requirement, skip to the next dataset
    if infos['final_number_features'] >= 3 and infos['final_number_rows'] >= 30:
        print('Feature and observations fulfill requirements.')
        
    
        # Extract the target feature to the dense_df
        dense_df[row['target_feature']] = df[row['target_feature']].iloc[dense_df.index,]
        dense_df = dense_df.reset_index(drop=True)
        dense_df.to_csv('../data folder/dense_dfs/'+str(row['dataset_id'])+'.csv', index=False)
        
        # Train the models for dense_df and get the metrics
        for model in models:
            metric, result, normalized_accuracy = trainAutogluonModels(dense_df, '../AutoGluonModels/' + 'final_' + model + '_' + row['dataset_name'], 
                                                            row['problem_type'], row['target_feature'], {model:{}}, row['num_classes'])
            infos['final_' + model + '_' + metric] = result
            infos['final_' + model + '_normalized_accuracy'] = normalized_accuracy


    binary_feature = None
    for feature in dense_df.columns:
        if dense_df[feature].nunique() == 2:
            binary_feature = feature
            break

    # Append the dataset id and name
    infos['dataset_id'] = row['dataset_id']
    infos['dataset_name'] = row['dataset_name']
    infos['binary_feature'] = binary_feature


    # Append the row (dataset results) to the final table
    final_table.loc[len(final_table)] = infos

46904
Total features: 5 Total rows: 1503
Original density: 0.0010519022423784328

Features left: 4 Rows left: 1503
Final density: 0.11044973544973545

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46905
Total features: 9 Total rows: 32769
Original density: 5.4331464888837344e-21

Features left: 1 Rows left: 67
Final density: 1.0

Model already exists. Loading...
Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46906
Total features: 38 Total rows: 886
Original density: 6.763894527119904e-16

Features left: 13 Rows left: 9
Final density: 0.140625

Model already exists. Loading...
Model already exists. Loading...
46907
Total features: 7 Total rows: 1515
Original density: 5.646737052785582e-10

Features left: 3 Rows left: 34
Final density: 0.3541666666666667

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46908
Total features: 170 Total rows: 76000
Original density: 0.0

Features left: 3 Rows left: 52
Final density: 0.8666666666666667

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46910
Total features: 13 Total rows: 44905
Original density: 5.349772965830006e-12

Features left: 8 Rows left: 2533
Final density: 0.18323206018518517

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46911
Total features: 10 Total rows: 10000
Original density: 4.6085769342056656e-12

Features left: 6 Rows left: 723
Final density: 0.6846590909090909

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46912
Total features: 1776 Total rows: 3751
Original density: 0.0

Features left: 9 Rows left: 87
Final density: 0.169921875

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46913
Total features: 4 Total rows: 502
Original density: 0.0001906424193814223

Features left: 2 Rows left: 188
Final density: 0.18377321603128055

Model already exists. Loading...
Model already exists. Loading...
46915
Total features: 19 Total rows: 5000
Original density: 2.774980106523841e-36

Features left: 5 Rows left: 625
Final density: 0.24801587301587302

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46916
Total features: 85 Total rows: 8261
Original density: 4.188386241439141e-67

Features left: 6 Rows left: 17
Final density: 0.17708333333333334

Model already exists. Loading...
Model already exists. Loading...
46917
Total features: 8 Total rows: 996
Original density: 3.0385513323393077e-15

Features left: 2 Rows left: 452
Final density: 0.20829493087557605

Model already exists. Loading...
Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46918
Total features: 20 Total rows: 1000
Original density: 1.4033527721394342e-13

Features left: 7 Rows left: 128
Final density: 0.14814814814814814

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46919
Total features: 23 Total rows: 29944
Original density: 4.9283839727975495e-57

Features left: 4 Rows left: 201
Final density: 0.35892857142857143

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46920
Total features: 21 Total rows: 129880
Original density: 1.8612414495883584e-18

Features left: 8 Rows left: 16181
Final density: 0.20808899176954732

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46921
Total features: 8 Total rows: 768
Original density: 1.1174982314123598e-13

Features left: 2 Rows left: 283
Final density: 0.3541927409261577

Model already exists. Loading...
Model already exists. Loading...
46922
Total features: 47 Total rows: 71518
Original density: 7.57843832073672e-37

Features left: 9 Rows left: 9
Final density: 0.140625

Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

46923
Total features: 9 Total rows: 53595
Original density: 2.616386759811203e-13

Features left: 3 Rows left: 276
Final density: 0.9857142857142858

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46924
Total features: 10 Total rows: 10999
Original density: 9.03257841376853e-09

Features left: 7 Rows left: 4761
Final density: 0.22041666666666668

Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46927
Total features: 6 Total rows: 1499
Original density: 1.051149451208826e-05

Features left: 4 Rows left: 176
Final density: 0.11027568922305764

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46928
Total features: 9 Total rows: 45242
Original density: 5.407391379869e-16

Features left: 4 Rows left: 3221
Final density: 0.3268060064935065

Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46929
Total features: 10 Total rows: 149354
Original density: 1.066472191353621e-19

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

Features left: 3 Rows left: 323
Final density: 0.11945266272189349

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46930
Total features: 30 Total rows: 2400
Original density: 4.281293536606587e-90

Features left: 1 Rows left: 781
Final density: 1.0

Model already exists. Loading...
Model already exists. Loading...
46931
Total features: 6 Total rows: 1335
Original density: 0.0005399227364497593

Features left: 5 Rows left: 986
Final density: 0.21852836879432624

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46932
Total features: 23 Total rows: 9871
Original density: 1.4832573002592818e-35

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

Features left: 3 Rows left: 184
Final density: 0.13529411764705881

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

46933
Total features: 1617 Total rows: 3825
Original density: 0.0

Features left: 9 Rows left: 55
Final density: 0.107421875

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46934
Total features: 8 Total rows: 20640
Original density: 5.234241194407872e-22

Features left: 2 Rows left: 11032
Final density: 0.25136711629602626

Model already exists. Loading...
Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46935
Total features: 12 Total rows: 19084
Original density: 5.30889048214203e-10

Features left: 6 Rows left: 1004
Final density: 0.10671768707482993

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

46937
Total features: 24 Total rows: 12587
Original density: 1.445596993304525e-11

Features left: 9 Rows left: 178
Final density: 0.1545138888888889

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46938
Total features: 13 Total rows: 1723
Original density: 1.3356526487161817e-10

Features left: 7 Rows left: 444
Final density: 0.20555555555555555

Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Model already exists. Loading...
46939
Total features: 212 Total rows: 50000
Original density: 0.0

Features left: 9 Rows left: 27
Final density: 0.10546875

Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

46940
Total features: 25 Total rows: 2039
Original density: 3.46008068054626e-32

Features left: 8 Rows left: 67
Final density: 0.11631944444444445

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

46941
Total features: 6 Total rows: 416
Original density: 7.372958257713248e-06

Features left: 2 Rows left: 40
Final density: 0.3125

Model already exists. Loading...
Model already exists. Loading...
46942
Total features: 15 Total rows: 13776
Original density: 1.011417240408681e-44

Features left: 4 Rows left: 2812
Final density: 0.24409722222222222

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46980
Total features: 111 Total rows: 1699
Original density: 1.038332178849761e-68

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

Features left: 6 Rows left: 52
Final density: 0.10699588477366255

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46969
Total features: 86 Total rows: 7395
Original density: 9.557813484108812e-23

Features left: 9 Rows left: 52
Final density: 0.1015625

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

46947
Total features: 17 Total rows: 12205
Original density: 1.3093726543475288e-29

Features left: 5 Rows left: 374
Final density: 0.14429012345679013

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

46949
Total features: 9 Total rows: 43974
Original density: 4.142388833151155e-35

Features left: 1 Rows left: 341
Final density: 1.0

Model already exists. Loading...
Model already exists. Loading...
46950
Total features: 64 Total rows: 5850
Original density: 9.503573095074777e-236

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

Features left: 1 Rows left: 3255
Final density: 1.0003073140749847

Model already exists. Loading...
Model already exists. Loading...
46952
Total features: 41 Total rows: 1051
Original density: 2.447263710241777e-63

Features left: 5 Rows left: 15
Final density: 0.15625

Model already exists. Loading...
Model already exists. Loading...
46953
Total features: 1024 Total rows: 5259
Original density: 2.925415855472343e-305

Features left: 9 Rows left: 60
Final density: 0.1171875

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46954
Total features: 6 Total rows: 774
Original density: 7.633914023940202e-10

Features left: 2 Rows left: 23
Final density: 0.6571428571428571

Model already exists. Loading...
Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46955
Total features: 11 Total rows: 78053
Original density: 2.0754355569286495e-42

Features left: 2 Rows left: 6000
Final density: 1.0

Model already exists. Loading...
Model already exists. Loading...
46956
Total features: 15 Total rows: 2578
Original density: 9.400295346125563e-18

Features left: 6 Rows left: 53
Final density: 0.1840277777777778

Model already exists. Loading...
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\psyey\OneDrive\Escritorio\Git_repos\Tabular-ML-Autogluon-with-dense-data-tensors\.venvTabArenaAnalysis\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

46958
Total features: 60 Total rows: 3005
Original density: 6.838044444444444e-38

Features left: 7 Rows left: 2554
Final density: 0.1558837890625

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46960
Total features: 36 Total rows: 4424
Original density: 1.2905192552173215e-40

Features left: 9 Rows left: 175
Final density: 0.11393229166666667

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46961
Total features: 81 Total rows: 15170
Original density: 3.872284267669358e-287

Features left: 2 Rows left: 45
Final density: 0.7142857142857143

Model already exists. Loading...
Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46962
Total features: 94 Total rows: 6819
Original density: 0.0

Features left: 2 Rows left: 389
Final density: 0.510498687664042

Model already exists. Loading...
Model already exists. Loading...
46963
Total features: 9 Total rows: 676
Original density: 0.0772748056698674

Features left: 8 Rows left: 558
Final density: 0.19135802469135801

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...
46964
Total features: 12 Total rows: 5320
Original density: 4.506093482946806e-22

Features left: 3 Rows left: 2368
Final density: 0.12550349798600804

Model already exists. Loading...
Model already exists. Loading...
Feature and observations fulfill requirements.
Model already exists. Loading...
Model already exists. Loading...

C:\Users\psyey\AppData\Local\Temp\ipykernel_15708\1481151833.py:74: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_table.loc[len(final_table)] = infos

46979
Total features: 21 Total rows: 8824
Original density: 3.679058450207553e-50

Features left: 2 Rows left: 227
Final density: 0.13757575757575757

Model already exists. Loading...
Model already exists. Loading...

In [12]:
json.dump( all_densities, open( "../results files/all_densities.json", 'w' ) )
final_table.to_csv('../results files/final_table.csv', index=False)

In [8]:
final_table

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,initial_XGB_normalized_accuracy,final_XGB_r2,final_XGB_accuracy,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy
0,46904,airfoil_self_noise,5,4,1503,1503,1.051902e-03,0.110450,None,0.950645,...,NaN,0.923800,NaN,NaN,0.947991,NaN,NaN,0.928413,NaN,NaN
1,46905,Amazon_employee_access,9,1,32769,67,5.433146e-21,1.000000,None,NaN,...,0.884447,NaN,NaN,NaN,NaN,0.944563,0.889126,NaN,NaN,NaN
2,46906,anneal,38,13,886,9,6.763895e-16,0.140625,bf,NaN,...,0.976852,NaN,NaN,NaN,NaN,0.992593,0.990741,NaN,NaN,NaN
3,46907,Another-Dataset-on-used-Fiat-500,7,3,1515,34,5.646737e-10,0.354167,None,0.830676,...,NaN,-0.180396,NaN,NaN,0.836072,NaN,NaN,-0.064585,NaN,NaN
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.984474,NaN,0.937500,0.875000,NaN,0.992325,0.984649,NaN,0.750000,0.500000
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.784577,NaN,0.886842,0.773684,NaN,0.895827,0.791654,NaN,0.888158,0.776316
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.714000,NaN,0.801843,0.603687,NaN,0.847333,0.694667,NaN,0.806452,0.612903
7,46912,Bioresponse,1776,9,3751,87,0.000000e+00,0.169922,D1736,NaN,...,0.548845,NaN,0.629630,0.259259,NaN,0.761989,0.523979,NaN,0.629630,0.259259
8,46913,blood-transfusion-service-center,4,2,502,188,1.906424e-04,0.183773,None,NaN,...,0.440000,NaN,NaN,NaN,NaN,0.733333,0.466667,NaN,NaN,NaN
9,46915,churn,19,5,5000,625,2.774980e-36,0.248016,international_plan,NaN,...,0.910667,NaN,0.771277,0.542553,NaN,0.918667,0.837333,NaN,0.792553,0.585106
10,46916,coil2000_insurance_policies,85,6,8261,17,4.188386e-67,0.177083,contributionBicyclePolicies,NaN,...,0.867662,NaN,NaN,NaN,NaN,0.933152,0.866305,NaN,NaN,NaN
11,46917,concrete_compressive_strength,8,2,996,452,3.038551e-15,0.208295,None,0.867073,...,NaN,NaN,NaN,NaN,0.884803,NaN,NaN,NaN,NaN,NaN
12,46918,credit-g,20,7,1000,128,1.403353e-13,0.148148,people_liable,NaN,...,0.473333,NaN,0.666667,0.333333,NaN,0.720000,0.440000,NaN,0.717949,0.435897
13,46919,credit_card_clients_default,23,4,29944,201,4.928384e-57,0.358929,SEX,NaN,...,0.642889,NaN,0.590164,0.180328,NaN,0.818778,0.637556,NaN,0.688525,0.377049
14,46920,customer_satisfaction_in_airline,21,8,129880,16181,1.861241e-18,0.208089,CustomerType,NaN,...,0.909814,NaN,0.793615,0.587230,NaN,0.947105,0.894210,NaN,0.798764,0.597528
15,46921,diabetes,8,2,768,283,1.117498e-13,0.354193,None,NaN,...,0.532468,NaN,NaN,NaN,NaN,0.761905,0.523810,NaN,NaN,NaN
16,46922,Diabetes130US,47,9,71518,9,7.578438e-37,0.140625,tolazamide,NaN,...,0.828020,NaN,NaN,NaN,NaN,0.914010,0.828020,NaN,NaN,NaN
17,46923,diamonds,9,3,53595,276,2.616387e-13,0.985714,None,0.981644,...,NaN,-0.048643,NaN,NaN,0.977045,NaN,NaN,-0.026704,NaN,NaN
18,46924,E-CommereShippingData,10,7,10999,4761,9.032578e-09,0.220417,Gender,NaN,...,0.343636,NaN,0.592022,0.184045,NaN,0.670303,0.340606,NaN,0.599020,0.198041
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.528889,NaN,0.754717,0.509434,NaN,0.802222,0.604444,NaN,0.811321,0.622642
20,46928,Food_Delivery_Time,9,4,45242,3221,5.407391e-16,0.326806,None,0.376339,...,NaN,0.503811,NaN,NaN,0.312180,NaN,NaN,0.461866,NaN,NaN
21,46929,GiveMeSomeCredit,10,3,149354,323,1.066472e-19,0.119453,FinancialDistressNextTwoYears,NaN,...,0.871867,NaN,0.659794,0.319588,NaN,0.934778,0.869556,NaN,0.639175,0.278351
22,46930,hazelnut-spread-contaminant-detection,30,1,2400,781,4.281294e-90,1.000000,None,NaN,...,0.836111,NaN,NaN,NaN,NaN,0.931944,0.863889,NaN,NaN,NaN
23,46931,healthcare_insurance_expenses,6,5,1335,986,5.399227e-04,0.218528,sex,0.806058,...,NaN,0.614456,NaN,NaN,0.803626,NaN,NaN,0.610852,NaN,NaN
24,46932,heloc,23,3,9871,184,1.483257e-35,0.135294,RiskPerformance,NaN,...,0.454430,NaN,0.714286,0.428571,NaN,0.715424,0.430848,NaN,0.714286,0.428571
25,46933,hiva_agnostic,1617,9,3825,55,0.000000e+00,0.107422,molecule_structure_property_1609,NaN,...,0.944107,NaN,0.823529,0.735294,NaN,0.962738,0.944107,NaN,0.823529,0.735294
26,46934,houses,8,2,20640,11032,5.234241e-22,0.251367,None,0.846846,...,NaN,NaN,NaN,NaN,0.824988,NaN,NaN,NaN,NaN,NaN
27,46935,HR_Analytics_Job_Change_of_Data_Scientists,12,6,19084,1004,5.308890e-10,0.106718,relevent_experience,NaN,...,0.589422,NaN,0.731788,0.463576,NaN,0.793145,0.586291,NaN,0.741722,0.483444
28,46937,in_vehicle_coupon_recommendation,24,9,12587,178,1.445597e-11,0.154514,expiration,NaN,...,0.521808,NaN,0.518519,0.037037,NaN,0.740147,0.480294,NaN,0.444444,-0.111111
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.756286,NaN,0.917910,0.835821,NaN,0.882012,0.764023,NaN,0.917910,0.835821
30,46939,kddcup09_appetency,212,9,50000,27,0.000000e+00,0.105469,Var116,NaN,...,0.961600,NaN,NaN,NaN,NaN,0.980800,0.961600,NaN,NaN,NaN
31,46940,Marketing_Campaign,25,8,2039,67,3.460081e-32,0.116319,AcceptedCmp3,NaN,...,0.773810,NaN,0.571429,0.142857,NaN,0.888393,0.776786,NaN,0.571429,0.142857
32,46941,maternal_health_risk,6,2,416,40,7.372958e-06,0.312500,None,NaN,...,0.665574,NaN,NaN,NaN,NaN,0.688525,0.532787,NaN,NaN,NaN
33,46942,miami_housing,15,4,13776,2812,1.011417e-44,0.244097,avno60plus,0.925494,...,NaN,0.321257,NaN,NaN,0.911543,NaN,NaN,0.260518,NaN,NaN
34,46980,MIC,111,6,1699,52,1.038332e-68,0.106996,SEX,NaN,...,0.865546,NaN,0.875000,0.857143,NaN,0.868627,0.849860,NaN,0.875000,0.857143
35,46969,NATICUSdroid,86,9,7395,52,9.557813e-23,0.101562,com.android.launcher.permission.UNINSTALL_SHOR...,NaN,...,0.886121,NaN,0.812500,0.625000,NaN,0.943060,0.886121,NaN,0.812500,0.625000
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.792917,NaN,0.858407,0.716814,NaN,0.889159,0.778318,NaN,0.884956,0.769912
37,46949,physiochemical_protein,9,1,43974,341,4.142389e-35,1.000000,None,0.644327,...,NaN,NaN,NaN,NaN,0.579676,NaN,NaN,NaN,NaN,NaN
38,46950,polish_companies_bankruptcy,64,1,5850,3255,9.503573e-236,1.000307,None,NaN,...,0.922166,NaN,NaN,NaN,NaN,0.950931,0.901861,NaN,NaN,NaN
39,46952,qsar-biodeg,41,5,1051,15,2.447264e-63,0.156250,Presence_CBr_At_Dist1,NaN,...,0.716088,NaN,NaN,NaN,NaN,0.813880,0.627760,NaN,NaN,NaN
40,46953,QSAR-TID-11,1024,9,5259,60,2.925416e-305,0.117188,FCFP6_1024_1015,0.747177,...,NaN,-0.074484,NaN,NaN,0.748240,NaN,NaN,-0.340889,NaN,NaN
41,46954,QSAR_fish_toxicity,6,2,774,23,7.633914e-10,0.657143,None,0.465542,...,NaN,NaN,NaN,NaN,0.524539,NaN,NaN,NaN,NaN,NaN
42,46955,SDSS17,11,2,78053,6000,2.075436e-42,1.000000,None,NaN,...,0.967458,NaN,NaN,NaN,NaN,0.971686,0.957529,NaN,NaN,NaN
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.840206,NaN,0.937500,0.875000,NaN,0.920103,0.840206,NaN,0.937500,0.875000
44,46958,splice,60,7,3005,2554,6.838044e-38,0.155884,None,NaN,...,0.949843,NaN,0.582790,0.374185,NaN,0.935214,0.902821,NaN,0.585398,0.378096
45,46960,students_dropout_and_academic_success,36,9,4424,175,1.290519e-40,0.113932,Daytimeevening_attendance,NaN,...,0.662274,NaN,0.566038,0.349057,NaN,0.742470,0.613705,NaN,0.528302,0.292453
46,46961,superconductivity,81,2,15170,45,3.872284e-287,0.714286,None,0.917708,...,NaN,NaN,NaN,NaN,0.898582,NaN,NaN,NaN,NaN,NaN
47,46962,taiwanese_bankruptcy_prediction,94,2,6819,389,0.000000e+00,0.510499,Liability_Assets_Flag,NaN,...,0.938416,NaN,NaN,NaN,NaN,0.968719,0.937439,NaN,NaN,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.822660,NaN,0.773810,0.660714,NaN,0.862069,0.793103,NaN,0.767857,0.651786
49,46964,wine_quality,12,3,5320,2368,4.506093e-22,0.125503,wine_color,0.449589,...,NaN,0.070603,NaN,NaN,0.320265,NaN,NaN,0.043394,NaN,NaN
50,46979,jm1,21,2,8824,227,3.679058e-50,0.137576,None,NaN,...,0.627067,NaN,NaN,NaN,NaN,0.814758,0.629516,NaN,NaN,NaN

In [50]:
final_table

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,initial_XGB_normalized_accuracy,final_XGB_r2,final_XGB_accuracy,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy
0,46904,airfoil_self_noise,5,4,1503,1503,1.051902e-03,0.110450,None,0.939926,...,NaN,0.930319,NaN,NaN,0.946526,NaN,NaN,0.945005,NaN,NaN
1,46905,Amazon_employee_access,9,1,32769,67,5.433146e-21,1.000000,None,NaN,...,0.888312,NaN,NaN,NaN,NaN,0.943444,0.886888,NaN,NaN,NaN
2,46906,anneal,38,13,886,8,6.763895e-16,0.125000,bl,NaN,...,0.986111,NaN,NaN,NaN,NaN,0.992593,0.990741,NaN,NaN,NaN
3,46907,Another-Dataset-on-used-Fiat-500,7,3,1515,34,5.646737e-10,0.354167,None,0.825045,...,NaN,0.520440,NaN,NaN,0.831274,NaN,NaN,-0.104609,NaN,NaN
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.987018,NaN,0.812500,0.625000,NaN,0.992588,0.985175,NaN,0.812500,0.625000
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.777499,NaN,0.853947,0.707895,NaN,0.891109,0.782218,NaN,0.856579,0.713158
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.700000,NaN,0.829493,0.658986,NaN,0.849667,0.699333,NaN,0.815668,0.631336
7,46912,Bioresponse,1776,11,3751,255,0.000000e+00,0.124512,D1216,NaN,...,0.571936,NaN,0.584416,0.168831,NaN,0.758437,0.516874,NaN,0.545455,0.090909
8,46913,blood-transfusion-service-center,4,2,502,188,1.906424e-04,0.183773,None,NaN,...,0.448889,NaN,NaN,NaN,NaN,0.777778,0.555556,NaN,NaN,NaN
9,46915,churn,19,5,5000,625,2.774980e-36,0.248016,international_plan,NaN,...,0.905333,NaN,0.707447,0.414894,NaN,0.913333,0.826667,NaN,0.739362,0.478723
10,46916,coil2000_insurance_policies,85,7,8261,29,4.188386e-67,0.100694,contributionBicyclePolicies,NaN,...,0.883950,NaN,NaN,NaN,NaN,0.939600,0.879199,NaN,NaN,NaN
11,46917,concrete_compressive_strength,8,2,996,452,3.038551e-15,0.208295,None,0.898137,...,NaN,NaN,NaN,NaN,0.918552,NaN,NaN,NaN,NaN,NaN
12,46918,credit-g,20,7,1000,164,1.403353e-13,0.189815,people_liable,NaN,...,0.600000,NaN,0.620000,0.240000,NaN,0.783333,0.566667,NaN,0.600000,0.200000
13,46919,credit_card_clients_default,23,4,29944,187,4.928384e-57,0.333929,SEX,NaN,...,0.636000,NaN,0.736842,0.473684,NaN,0.816111,0.632222,NaN,0.701754,0.403509
14,46920,customer_satisfaction_in_airline,21,8,129880,8960,1.861241e-18,0.115226,CustomerType,NaN,...,0.912432,NaN,0.918527,0.837054,NaN,0.953342,0.906683,NaN,0.890625,0.781250
15,46921,diabetes,8,2,768,283,1.117498e-13,0.354193,None,NaN,...,0.471861,NaN,NaN,NaN,NaN,0.718615,0.437229,NaN,NaN,NaN
16,46922,Diabetes130US,47,9,71518,7,7.578438e-37,0.109375,tolbutamide,NaN,...,0.821588,NaN,NaN,NaN,NaN,0.910328,0.820656,NaN,NaN,NaN
17,46923,diamonds,9,3,53595,276,2.616387e-13,0.985714,None,0.980541,...,NaN,0.022798,NaN,NaN,0.975334,NaN,NaN,-0.066406,NaN,NaN
18,46924,E-CommereShippingData,10,7,10999,4761,9.032578e-09,0.220417,Gender,NaN,...,0.313333,NaN,0.585724,0.171449,NaN,0.653636,0.307273,NaN,0.594822,0.189643
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.528889,NaN,0.792453,0.584906,NaN,0.777778,0.555556,NaN,0.792453,0.584906
20,46928,Food_Delivery_Time,9,4,45242,3221,5.407391e-16,0.326806,None,0.377846,...,NaN,0.488820,NaN,NaN,0.294570,NaN,NaN,0.390429,NaN,NaN
21,46929,GiveMeSomeCredit,10,3,149354,323,1.066472e-19,0.119453,FinancialDistressNextTwoYears,NaN,...,0.871111,NaN,0.494845,-0.010309,NaN,0.934422,0.868844,NaN,0.639175,0.278351
22,46930,hazelnut-spread-contaminant-detection,30,1,2400,781,4.281294e-90,1.000000,None,NaN,...,0.805556,NaN,NaN,NaN,NaN,0.911111,0.822222,NaN,NaN,NaN
23,46931,healthcare_insurance_expenses,6,5,1335,986,5.399227e-04,0.218528,sex,0.807423,...,NaN,0.646636,NaN,NaN,0.800976,NaN,NaN,0.630632,NaN,NaN
24,46932,heloc,23,3,9871,184,1.483257e-35,0.135294,RiskPerformance,NaN,...,0.435309,NaN,0.803571,0.607143,NaN,0.717973,0.435946,NaN,0.803571,0.607143
25,46933,hiva_agnostic,1617,9,3825,63,0.000000e+00,0.123047,molecule_structure_property_534,NaN,...,0.953206,NaN,0.947368,0.921053,NaN,0.968804,0.953206,NaN,0.947368,0.921053
26,46934,houses,8,2,20640,11032,5.234241e-22,0.251367,None,0.849217,...,NaN,NaN,NaN,NaN,0.830619,NaN,NaN,NaN,NaN,NaN
27,46935,HR_Analytics_Job_Change_of_Data_Scientists,12,6,19084,1731,5.308890e-10,0.183992,relevent_experience,NaN,...,0.595685,NaN,0.726923,0.453846,NaN,0.795059,0.590118,NaN,0.732692,0.465385
28,46937,in_vehicle_coupon_recommendation,24,9,12587,178,1.445597e-11,0.154514,expiration,NaN,...,0.502365,NaN,0.592593,0.185185,NaN,0.745402,0.490804,NaN,0.518519,0.037037
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.736944,NaN,0.917910,0.835821,NaN,0.885880,0.771760,NaN,0.917910,0.835821
30,46939,kddcup09_appetency,212,8,50000,14,0.000000e+00,0.109375,Var2,NaN,...,0.962800,NaN,NaN,NaN,NaN,0.981067,0.962133,NaN,NaN,NaN
31,46940,Marketing_Campaign,25,8,2039,67,3.460081e-32,0.116319,AcceptedCmp3,NaN,...,0.750000,NaN,0.666667,0.333333,NaN,0.886905,0.773810,NaN,0.619048,0.238095
32,46941,maternal_health_risk,6,2,416,40,7.372958e-06,0.312500,None,NaN,...,0.695082,NaN,NaN,NaN,NaN,0.642623,0.463934,NaN,NaN,NaN
33,46942,miami_housing,15,4,13776,2812,1.011417e-44,0.244097,avno60plus,0.922270,...,NaN,0.303364,NaN,NaN,0.913591,NaN,NaN,0.142900,NaN,NaN
34,46980,MIC,111,5,1699,37,1.038332e-68,0.228395,SEX,NaN,...,0.872269,NaN,0.666667,0.619048,NaN,0.876471,0.858824,NaN,0.250000,0.142857
35,46969,NATICUSdroid,86,9,7395,69,9.557813e-23,0.134766,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,NaN,...,0.874555,NaN,0.857143,0.714286,NaN,0.936833,0.873665,NaN,0.952381,0.904762
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.801568,NaN,0.849558,0.699115,NaN,0.900243,0.800487,NaN,0.849558,0.699115
37,46949,physiochemical_protein,9,1,43974,341,4.142389e-35,1.000000,None,0.645328,...,NaN,NaN,NaN,NaN,0.610251,NaN,NaN,NaN,NaN,NaN
38,46950,polish_companies_bankruptcy,64,1,5850,3255,9.503573e-236,1.000307,None,NaN,...,0.950367,NaN,NaN,NaN,NaN,0.950931,0.901861,NaN,NaN,NaN
39,46952,qsar-biodeg,41,5,1051,15,2.447264e-63,0.156250,Presence_CBr_At_Dist1,NaN,...,0.665615,NaN,NaN,NaN,NaN,0.864353,0.728707,NaN,NaN,NaN
40,46953,QSAR-TID-11,1024,9,5259,53,2.925416e-305,0.103516,FCFP6_1024_342,0.724764,...,NaN,-0.020767,NaN,NaN,0.733659,NaN,NaN,-0.160186,NaN,NaN
41,46954,QSAR_fish_toxicity,6,2,774,23,7.633914e-10,0.657143,None,0.544628,...,NaN,NaN,NaN,NaN,0.535097,NaN,NaN,NaN,NaN,NaN
42,46955,SDSS17,11,2,78053,6000,2.075436e-42,1.000000,None,NaN,...,0.965024,NaN,NaN,NaN,NaN,0.968141,0.952212,NaN,NaN,NaN
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.860825,NaN,0.875000,0.750000,NaN,0.934278,0.868557,NaN,0.875000,0.750000
44,46958,splice,60,7,3005,2519,6.838044e-38,0.153748,None,NaN,...,0.929467,NaN,0.576720,0.365079,NaN,0.938349,0.907524,NaN,0.628307,0.442460
45,46960,students_dropout_and_academic_success,36,9,4424,175,1.290519e-40,0.113932,Daytimeevening_attendance,NaN,...,0.635166,NaN,0.547170,0.320755,NaN,0.762801,0.644202,NaN,0.603774,0.405660
46,46961,superconductivity,81,2,15170,45,3.872284e-287,0.714286,None,0.920797,...,NaN,NaN,NaN,NaN,0.912115,NaN,NaN,NaN,NaN,NaN
47,46962,taiwanese_bankruptcy_prediction,94,2,6819,389,0.000000e+00,0.510499,Liability_Assets_Flag,NaN,...,0.933529,NaN,NaN,NaN,NaN,0.965787,0.931574,NaN,NaN,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.870690,NaN,0.779762,0.669643,NaN,0.891626,0.837438,NaN,0.803571,0.705357
49,46964,wine_quality,12,3,5320,2368,4.506093e-22,0.125503,wine_color,0.467736,...,NaN,0.052098,NaN,NaN,0.352707,NaN,NaN,0.045309,NaN,NaN
50,46979,jm1,21,2,8824,227,3.679058e-50,0.137576,None,NaN,...,0.618494,NaN,NaN,NaN,NaN,0.810778,0.621555,NaN,NaN,NaN

# Scatter plots

In [51]:
def calculateInitialFinalImprovement(x):
    if pd.notna(x.initial_XGB_r2):
        return (x.final_XGB_r2 - x.initial_XGB_r2)/abs(x.initial_XGB_r2) * 100
    else:
        return (x.final_XGB_normalized_accuracy - x.initial_XGB_normalized_accuracy)/abs(x.initial_XGB_normalized_accuracy) * 100 
final_table['final_improvement_xgb'] = final_table.apply(lambda x : calculateInitialFinalImprovement(x), axis=1)
final_table['final_improvement_accuracy'] = final_table.apply(lambda x : (x.final_XGB_normalized_accuracy - x.final_NN_TORCH_normalized_accuracy)/x.final_XGB_normalized_accuracy * 100, axis=1)
final_table['final_improvement_r2'] = final_table.apply(lambda x : (x.final_XGB_r2 - x.final_NN_TORCH_r2)/x.final_XGB_r2 * 100, axis=1)
final_table

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy,final_improvement_xgb,final_improvement_accuracy,final_improvement_r2
0,46904,airfoil_self_noise,5,4,1503,1503,1.051902e-03,0.110450,None,0.939926,...,NaN,0.946526,NaN,NaN,0.945005,NaN,NaN,-1.022182,NaN,-1.578600
1,46905,Amazon_employee_access,9,1,32769,67,5.433146e-21,1.000000,None,NaN,...,NaN,NaN,0.943444,0.886888,NaN,NaN,NaN,NaN,NaN,NaN
2,46906,anneal,38,13,886,8,6.763895e-16,0.125000,bl,NaN,...,NaN,NaN,0.992593,0.990741,NaN,NaN,NaN,NaN,NaN,NaN
3,46907,Another-Dataset-on-used-Fiat-500,7,3,1515,34,5.646737e-10,0.354167,None,0.825045,...,NaN,0.831274,NaN,NaN,-0.104609,NaN,NaN,-36.919769,NaN,120.100049
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.625000,NaN,0.992588,0.985175,NaN,0.812500,0.625000,-36.677924,0.000000,NaN
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.707895,NaN,0.891109,0.782218,NaN,0.856579,0.713158,-8.952359,-0.743494,NaN
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.658986,NaN,0.849667,0.699333,NaN,0.815668,0.631336,-5.859118,4.195804,NaN
7,46912,Bioresponse,1776,11,3751,255,0.000000e+00,0.124512,D1216,NaN,...,0.168831,NaN,0.758437,0.516874,NaN,0.545455,0.090909,-70.480761,46.153846,NaN
8,46913,blood-transfusion-service-center,4,2,502,188,1.906424e-04,0.183773,None,NaN,...,NaN,NaN,0.777778,0.555556,NaN,NaN,NaN,NaN,NaN,NaN
9,46915,churn,19,5,5000,625,2.774980e-36,0.248016,international_plan,NaN,...,0.414894,NaN,0.913333,0.826667,NaN,0.739362,0.478723,-54.172281,-15.384615,NaN
10,46916,coil2000_insurance_policies,85,7,8261,29,4.188386e-67,0.100694,contributionBicyclePolicies,NaN,...,NaN,NaN,0.939600,0.879199,NaN,NaN,NaN,NaN,NaN,NaN
11,46917,concrete_compressive_strength,8,2,996,452,3.038551e-15,0.208295,None,0.898137,...,NaN,0.918552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,46918,credit-g,20,7,1000,164,1.403353e-13,0.189815,people_liable,NaN,...,0.240000,NaN,0.783333,0.566667,NaN,0.600000,0.200000,-60.000000,16.666667,NaN
13,46919,credit_card_clients_default,23,4,29944,187,4.928384e-57,0.333929,SEX,NaN,...,0.473684,NaN,0.816111,0.632222,NaN,0.701754,0.403509,-25.521351,14.814815,NaN
14,46920,customer_satisfaction_in_airline,21,8,129880,8960,1.861241e-18,0.115226,CustomerType,NaN,...,0.837054,NaN,0.953342,0.906683,NaN,0.890625,0.781250,-8.261264,6.666667,NaN
15,46921,diabetes,8,2,768,283,1.117498e-13,0.354193,None,NaN,...,NaN,NaN,0.718615,0.437229,NaN,NaN,NaN,NaN,NaN,NaN
16,46922,Diabetes130US,47,9,71518,7,7.578438e-37,0.109375,tolbutamide,NaN,...,NaN,NaN,0.910328,0.820656,NaN,NaN,NaN,NaN,NaN,NaN
17,46923,diamonds,9,3,53595,276,2.616387e-13,0.985714,None,0.980541,...,NaN,0.975334,NaN,NaN,-0.066406,NaN,NaN,-97.674970,NaN,391.282534
18,46924,E-CommereShippingData,10,7,10999,4761,9.032578e-09,0.220417,Gender,NaN,...,0.171449,NaN,0.653636,0.307273,NaN,0.594822,0.189643,-45.282373,-10.612245,NaN
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.584906,NaN,0.777778,0.555556,NaN,0.792453,0.584906,10.591406,0.000000,NaN
20,46928,Food_Delivery_Time,9,4,45242,3221,5.407391e-16,0.326806,None,0.377846,...,NaN,0.294570,NaN,NaN,0.390429,NaN,NaN,29.370052,NaN,20.128306
21,46929,GiveMeSomeCredit,10,3,149354,323,1.066472e-19,0.119453,FinancialDistressNextTwoYears,NaN,...,-0.010309,NaN,0.934422,0.868844,NaN,0.639175,0.278351,-101.183463,2800.000000,NaN
22,46930,hazelnut-spread-contaminant-detection,30,1,2400,781,4.281294e-90,1.000000,None,NaN,...,NaN,NaN,0.911111,0.822222,NaN,NaN,NaN,NaN,NaN,NaN
23,46931,healthcare_insurance_expenses,6,5,1335,986,5.399227e-04,0.218528,sex,0.807423,...,NaN,0.800976,NaN,NaN,0.630632,NaN,NaN,-19.913625,NaN,2.475043
24,46932,heloc,23,3,9871,184,1.483257e-35,0.135294,RiskPerformance,NaN,...,0.607143,NaN,0.717973,0.435946,NaN,0.803571,0.607143,39.473959,0.000000,NaN
25,46933,hiva_agnostic,1617,9,3825,63,0.000000e+00,0.123047,molecule_structure_property_534,NaN,...,0.921053,NaN,0.968804,0.953206,NaN,0.947368,0.921053,-3.373206,0.000000,NaN
26,46934,houses,8,2,20640,11032,5.234241e-22,0.251367,None,0.849217,...,NaN,0.830619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,46935,HR_Analytics_Job_Change_of_Data_Scientists,12,6,19084,1731,5.308890e-10,0.183992,relevent_experience,NaN,...,0.453846,NaN,0.795059,0.590118,NaN,0.732692,0.465385,-23.811107,-2.542373,NaN
28,46937,in_vehicle_coupon_recommendation,24,9,12587,178,1.445597e-11,0.154514,expiration,NaN,...,0.185185,NaN,0.745402,0.490804,NaN,0.518519,0.037037,-63.137300,80.000000,NaN
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.835821,NaN,0.885880,0.771760,NaN,0.917910,0.835821,13.417166,0.000000,NaN
30,46939,kddcup09_appetency,212,8,50000,14,0.000000e+00,0.109375,Var2,NaN,...,NaN,NaN,0.981067,0.962133,NaN,NaN,NaN,NaN,NaN,NaN
31,46940,Marketing_Campaign,25,8,2039,67,3.460081e-32,0.116319,AcceptedCmp3,NaN,...,0.333333,NaN,0.886905,0.773810,NaN,0.619048,0.238095,-55.555556,28.571429,NaN
32,46941,maternal_health_risk,6,2,416,40,7.372958e-06,0.312500,None,NaN,...,NaN,NaN,0.642623,0.463934,NaN,NaN,NaN,NaN,NaN,NaN
33,46942,miami_housing,15,4,13776,2812,1.011417e-44,0.244097,avno60plus,0.922270,...,NaN,0.913591,NaN,NaN,0.142900,NaN,NaN,-67.106808,NaN,52.894769
34,46980,MIC,111,5,1699,37,1.038332e-68,0.228395,SEX,NaN,...,0.619048,NaN,0.876471,0.858824,NaN,0.250000,0.142857,-29.030186,76.923077,NaN
35,46969,NATICUSdroid,86,9,7395,69,9.557813e-23,0.134766,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,NaN,...,0.714286,NaN,0.936833,0.873665,NaN,0.952381,0.904762,-18.325825,-26.666667,NaN
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.699115,NaN,0.900243,0.800487,NaN,0.849558,0.699115,-12.781567,0.000000,NaN
37,46949,physiochemical_protein,9,1,43974,341,4.142389e-35,1.000000,None,0.645328,...,NaN,0.610251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,46950,polish_companies_bankruptcy,64,1,5850,3255,9.503573e-236,1.000307,None,NaN,...,NaN,NaN,0.950931,0.901861,NaN,NaN,NaN,NaN,NaN,NaN
39,46952,qsar-biodeg,41,5,1051,15,2.447264e-63,0.156250,Presence_CBr_At_Dist1,NaN,...,NaN,NaN,0.864353,0.728707,NaN,NaN,NaN,NaN,NaN,NaN
40,46953,QSAR-TID-11,1024,9,5259,53,2.925416e-305,0.103516,FCFP6_1024_342,0.724764,...,NaN,0.733659,NaN,NaN,-0.160186,NaN,NaN,-102.865327,NaN,-671.353974
41,46954,QSAR_fish_toxicity,6,2,774,23,7.633914e-10,0.657143,None,0.544628,...,NaN,0.535097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,46955,SDSS17,11,2,78053,6000,2.075436e-42,1.000000,None,NaN,...,NaN,NaN,0.968141,0.952212,NaN,NaN,NaN,NaN,NaN,NaN
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.750000,NaN,0.934278,0.868557,NaN,0.875000,0.750000,-12.874251,0.000000,NaN
44,46958,splice,60,7,3005,2519,6.838044e-38,0.153748,None,NaN,...,0.365079,NaN,0.938349,0.907524,NaN,0.628307,0.442460,-60.721647,-21.195652,NaN
45,46960,students_dropout_and_academic_success,36,9,4424,175,1.290519e-40,0.113932,Daytimeevening_attendance,NaN,...,0.320755,NaN,0.762801,0.644202,NaN,0.603774,0.405660,-49.500621,-26.470588,NaN
46,46961,superconductivity,81,2,15170,45,3.872284e-287,0.714286,None,0.920797,...,NaN,0.912115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,46962,taiwanese_bankruptcy_prediction,94,2,6819,389,0.000000e+00,0.510499,Liability_Assets_Flag,NaN,...,NaN,NaN,0.965787,0.931574,NaN,NaN,NaN,NaN,NaN,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.669643,NaN,0.891626,0.837438,NaN,0.803571,0.705357,-23.090523,-5.333333,NaN
49,46964,wine_quality,12,3,5320,2368,4.506093e-22,0.125503,wine_color,0.467736,...,NaN,0.352707,NaN,NaN,0.045309,NaN,NaN,-88.861654,NaN,13.031585
50,46979,jm1,21,2,8824,227,3.679058e-50,0.137576,None,NaN,...,NaN,NaN,0.810778,0.621555,NaN,NaN,NaN,NaN,NaN,NaN

In [131]:
final_table[(final_table['final_number_features'] >= 3) & (final_table['final_number_rows'] >= 30)]

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,initial_NN_TORCH_accuracy,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy,final_improvement_xgb,final_improvement_accuracy,final_improvement_r2
0,46904,airfoil_self_noise,5,4,1503,1503,1.051902e-03,0.110450,None,0.939926,...,NaN,0.946526,NaN,NaN,0.945005,NaN,NaN,-1.022182,NaN,-1.578600
3,46907,Another-Dataset-on-used-Fiat-500,7,3,1515,34,5.646737e-10,0.354167,None,0.825045,...,NaN,0.831274,NaN,NaN,-0.104609,NaN,NaN,-36.919769,NaN,120.100049
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.625000,NaN,0.992588,0.985175,NaN,0.812500,0.625000,-36.677924,0.000000,NaN
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.707895,NaN,0.891109,0.782218,NaN,0.856579,0.713158,-8.952359,-0.743494,NaN
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.658986,NaN,0.849667,0.699333,NaN,0.815668,0.631336,-5.859118,4.195804,NaN
7,46912,Bioresponse,1776,11,3751,255,0.000000e+00,0.124512,D1216,NaN,...,0.168831,NaN,0.758437,0.516874,NaN,0.545455,0.090909,-70.480761,46.153846,NaN
9,46915,churn,19,5,5000,625,2.774980e-36,0.248016,international_plan,NaN,...,0.414894,NaN,0.913333,0.826667,NaN,0.739362,0.478723,-54.172281,-15.384615,NaN
12,46918,credit-g,20,7,1000,164,1.403353e-13,0.189815,people_liable,NaN,...,0.240000,NaN,0.783333,0.566667,NaN,0.600000,0.200000,-60.000000,16.666667,NaN
13,46919,credit_card_clients_default,23,4,29944,187,4.928384e-57,0.333929,SEX,NaN,...,0.473684,NaN,0.816111,0.632222,NaN,0.701754,0.403509,-25.521351,14.814815,NaN
14,46920,customer_satisfaction_in_airline,21,8,129880,8960,1.861241e-18,0.115226,CustomerType,NaN,...,0.837054,NaN,0.953342,0.906683,NaN,0.890625,0.781250,-8.261264,6.666667,NaN
17,46923,diamonds,9,3,53595,276,2.616387e-13,0.985714,None,0.980541,...,NaN,0.975334,NaN,NaN,-0.066406,NaN,NaN,-97.674970,NaN,391.282534
18,46924,E-CommereShippingData,10,7,10999,4761,9.032578e-09,0.220417,Gender,NaN,...,0.171449,NaN,0.653636,0.307273,NaN,0.594822,0.189643,-45.282373,-10.612245,NaN
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.584906,NaN,0.777778,0.555556,NaN,0.792453,0.584906,10.591406,0.000000,NaN
20,46928,Food_Delivery_Time,9,4,45242,3221,5.407391e-16,0.326806,None,0.377846,...,NaN,0.294570,NaN,NaN,0.390429,NaN,NaN,29.370052,NaN,20.128306
21,46929,GiveMeSomeCredit,10,3,149354,323,1.066472e-19,0.119453,FinancialDistressNextTwoYears,NaN,...,-0.010309,NaN,0.934422,0.868844,NaN,0.639175,0.278351,-101.183463,2800.000000,NaN
23,46931,healthcare_insurance_expenses,6,5,1335,986,5.399227e-04,0.218528,sex,0.807423,...,NaN,0.800976,NaN,NaN,0.630632,NaN,NaN,-19.913625,NaN,2.475043
24,46932,heloc,23,3,9871,184,1.483257e-35,0.135294,RiskPerformance,NaN,...,0.607143,NaN,0.717973,0.435946,NaN,0.803571,0.607143,39.473959,0.000000,NaN
25,46933,hiva_agnostic,1617,9,3825,63,0.000000e+00,0.123047,molecule_structure_property_534,NaN,...,0.921053,NaN,0.968804,0.953206,NaN,0.947368,0.921053,-3.373206,0.000000,NaN
27,46935,HR_Analytics_Job_Change_of_Data_Scientists,12,6,19084,1731,5.308890e-10,0.183992,relevent_experience,NaN,...,0.453846,NaN,0.795059,0.590118,NaN,0.732692,0.465385,-23.811107,-2.542373,NaN
28,46937,in_vehicle_coupon_recommendation,24,9,12587,178,1.445597e-11,0.154514,expiration,NaN,...,0.185185,NaN,0.745402,0.490804,NaN,0.518519,0.037037,-63.137300,80.000000,NaN
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.835821,NaN,0.885880,0.771760,NaN,0.917910,0.835821,13.417166,0.000000,NaN
31,46940,Marketing_Campaign,25,8,2039,67,3.460081e-32,0.116319,AcceptedCmp3,NaN,...,0.333333,NaN,0.886905,0.773810,NaN,0.619048,0.238095,-55.555556,28.571429,NaN
33,46942,miami_housing,15,4,13776,2812,1.011417e-44,0.244097,avno60plus,0.922270,...,NaN,0.913591,NaN,NaN,0.142900,NaN,NaN,-67.106808,NaN,52.894769
34,46980,MIC,111,5,1699,37,1.038332e-68,0.228395,SEX,NaN,...,0.619048,NaN,0.876471,0.858824,NaN,0.250000,0.142857,-29.030186,76.923077,NaN
35,46969,NATICUSdroid,86,9,7395,69,9.557813e-23,0.134766,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,NaN,...,0.714286,NaN,0.936833,0.873665,NaN,0.952381,0.904762,-18.325825,-26.666667,NaN
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.699115,NaN,0.900243,0.800487,NaN,0.849558,0.699115,-12.781567,0.000000,NaN
40,46953,QSAR-TID-11,1024,9,5259,53,2.925416e-305,0.103516,FCFP6_1024_342,0.724764,...,NaN,0.733659,NaN,NaN,-0.160186,NaN,NaN,-102.865327,NaN,-671.353974
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.750000,NaN,0.934278,0.868557,NaN,0.875000,0.750000,-12.874251,0.000000,NaN
44,46958,splice,60,7,3005,2519,6.838044e-38,0.153748,None,NaN,...,0.365079,NaN,0.938349,0.907524,NaN,0.628307,0.442460,-60.721647,-21.195652,NaN
45,46960,students_dropout_and_academic_success,36,9,4424,175,1.290519e-40,0.113932,Daytimeevening_attendance,NaN,...,0.320755,NaN,0.762801,0.644202,NaN,0.603774,0.405660,-49.500621,-26.470588,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.669643,NaN,0.891626,0.837438,NaN,0.803571,0.705357,-23.090523,-5.333333,NaN
49,46964,wine_quality,12,3,5320,2368,4.506093e-22,0.125503,wine_color,0.467736,...,NaN,0.352707,NaN,NaN,0.045309,NaN,NaN,-88.861654,NaN,13.031585

In [52]:
final_table.to_csv('./final_table_medium_preset.csv', index=False)

In [71]:
import plotly.express as px
fig = px.scatter(final_table, x='final_density', y='final_improvement_xgb', size='final_number_rows')
fig.show()

In [51]:
import plotly.express as px
fig = px.scatter(final_table, x='final_density', y='final_improvement_xgb', size='final_number_rows')
fig.show()

In [72]:
import plotly.express as px
fig = px.scatter(final_table, x='final_density', y='final_improvement_accuracy')
fig.show()

In [54]:
import plotly.express as px
fig = px.scatter(final_table, x='final_density', y='final_improvement_accuracy')
fig.show()

In [53]:
fig = px.scatter(final_table, x='final_density', y='final_improvement_r2', size='final_number_rows')
fig.show()

# Histogram plots

In [169]:
fig = px.histogram(x=final_table['r2'].apply(lambda x: x * 100), nbins=10,
                   labels={'x':'r2'}, text_auto=True)
fig.update_layout(bargap=0.2)
fig.show()

In [168]:
fig = px.histogram(x=final_table['accuracy'].apply(lambda x: x * 100), nbins=10,
                   labels={'x':'Accuracy'}, text_auto=True)
fig.update_layout(bargap=0.2)
fig.show()

# Transform the binary feature (featurization)

In [209]:
df = pd.read_csv('./dense_dfs/46911.csv')

display(df)

df_wide = df.pivot(
    index=df.drop(columns=['gender', 'churn']),
    columns='gender',
    values='churn'
)
display(df_wide)

# Rename columns
df_wide.columns = [f"churn {col}" for col in df_wide.columns]

# Flatten the index to get a clean table
df_wide = df_wide.reset_index()

df_wide

,country,gender,tenure,products_number,credit_card,active_member,churn
0,Germany,Male,3,2,0,0,No
1,France,Male,1,2,1,1,No
2,Spain,Female,4,2,1,0,No
3,Germany,Male,8,2,1,1,No
4,Spain,Female,7,1,1,1,No
...,...,...,...,...,...,...,...
718,Germany,Male,3,4,1,0,Yes
719,Germany,Female,2,4,1,1,Yes
720,Spain,Female,1,3,0,0,Yes
721,Germany,Female,6,3,0,1,Yes
722,France,Female,9,4,1,0,Yes

gender                                                   Female Male
country tenure products_number credit_card active_member
France  0      1               0           0                Yes   No
                                           1                 No   No
                               1           0                Yes   No
                                           1                 No   No
               2               0           0                 No   No
...                                                         ...  ...
Spain   10     2               0           0                 No   No
                                           1                 No   No
                               1           0                 No  Yes
                                           1                 No   No
               3               0           0                NaN  Yes

[405 rows x 2 columns]

,country,tenure,products_number,credit_card,active_member,churn Female,churn Male
0,France,0,1,0,0,Yes,No
1,France,0,1,0,1,No,No
2,France,0,1,1,0,Yes,No
3,France,0,1,1,1,No,No
4,France,0,2,0,0,No,No
...,...,...,...,...,...,...,...
400,Spain,10,2,0,0,No,No
401,Spain,10,2,0,1,No,No
402,Spain,10,2,1,0,No,Yes
403,Spain,10,2,1,1,No,No
404,Spain,10,3,0,0,NaN,Yes

In [210]:
binary_columns = list(filter(lambda x: 'churn' in x,  df_wide.columns.values))
df_wide[binary_columns].isnull().mean().values * 100

array([ 8.88888889, 12.59259259])

In [218]:
df = pd.read_csv('./dense_dfs/46908.csv')

df = df.dropna(subset='ch_000')

display(df)

df_wide = df.pivot(
    index=df.drop(columns=['ch_000', 'AirPressureSystemFailure']),
    columns='ch_000',
    values='AirPressureSystemFailure'
)

display(df_wide)

# Rename columns
df_wide.columns = [f"AirPressureSystemFailure {col}" for col in df_wide.columns]

# Flatten the index to get a clean table
df_wide = df_wide.reset_index()

df_wide

       cd_000  ch_000  ef_000 AirPressureSystemFailure
0   1209600.0     0.0     0.0                      neg
2   1209600.0     0.0     NaN                      neg
5         NaN     0.0     0.0                      neg
7         NaN     0.0     NaN                      pos
8   1209600.0     0.0     2.0                      neg
9   1209600.0     0.0   252.0                      neg
11  1209600.0     0.0     6.0                      neg
12  1209600.0     0.0     4.0                      neg
14  1209600.0     0.0     8.0                      neg
16  1209600.0     0.0    82.0                      neg
17  1209600.0     0.0    20.0                      pos
18  1209600.0     0.0    10.0                      neg
19  1209600.0     0.0    18.0                      neg
20  1209600.0     0.0    26.0                      pos
21  1209600.0     0.0    12.0                      neg
22  1209600.0     0.0    14.0                      neg
24  1209600.0     0.0   482.0                      neg
25        NaN     0.0   350.0                      neg
26  1209600.0     0.0    84.0                      neg
27  1209600.0     2.0     0.0                      neg
28  1209600.0     0.0   166.0                      neg
29  1209600.0     0.0   320.0                      neg
31  1209600.0     0.0    22.0                      neg
32  1209600.0     0.0   236.0                      neg
35        NaN     0.0     2.0                      neg
36  1209600.0     0.0   276.0                      neg
39  1209600.0     0.0   134.0                      neg
40  1209600.0     0.0    28.0                      neg
41  1209600.0     0.0   144.0                      neg
42  1209600.0     0.0   350.0                      neg
43  1209600.0     0.0    86.0                      pos
46  1209600.0     0.0   340.0                      neg
47  1209600.0     0.0    74.0                      neg
49  1209600.0     0.0    30.0                      neg
50  1209600.0     0.0    40.0                      neg

ch_000            0.0  2.0
cd_000    ef_000
NaN       NaN     pos  NaN
          0.0     neg  NaN
          2.0     neg  NaN
          350.0   neg  NaN
1209600.0 NaN     neg  NaN
          0.0     neg  neg
          2.0     neg  NaN
          4.0     neg  NaN
          6.0     neg  NaN
          8.0     neg  NaN
          10.0    neg  NaN
          12.0    neg  NaN
          14.0    neg  NaN
          18.0    neg  NaN
          20.0    pos  NaN
          22.0    neg  NaN
          26.0    pos  NaN
          28.0    neg  NaN
          30.0    neg  NaN
          40.0    neg  NaN
          74.0    neg  NaN
          82.0    neg  NaN
          84.0    neg  NaN
          86.0    pos  NaN
          134.0   neg  NaN
          144.0   neg  NaN
          166.0   neg  NaN
          236.0   neg  NaN
          252.0   neg  NaN
          276.0   neg  NaN
          320.0   neg  NaN
          340.0   neg  NaN
          350.0   neg  NaN
          482.0   neg  NaN

,cd_000,ef_000,AirPressureSystemFailure 0.0,AirPressureSystemFailure 2.0
0,NaN,NaN,pos,NaN
1,NaN,0.0,neg,NaN
2,NaN,2.0,neg,NaN
3,NaN,350.0,neg,NaN
4,1209600.0,NaN,neg,NaN
5,1209600.0,0.0,neg,neg
6,1209600.0,2.0,neg,NaN
7,1209600.0,4.0,neg,NaN
8,1209600.0,6.0,neg,NaN
9,1209600.0,8.0,neg,NaN
10,1209600.0,10.0,neg,NaN
11,1209600.0,12.0,neg,NaN
12,1209600.0,14.0,neg,NaN
13,1209600.0,18.0,neg,NaN
14,1209600.0,20.0,pos,NaN
15,1209600.0,22.0,neg,NaN
16,1209600.0,26.0,pos,NaN
17,1209600.0,28.0,neg,NaN
18,1209600.0,30.0,neg,NaN
19,1209600.0,40.0,neg,NaN
20,1209600.0,74.0,neg,NaN
21,1209600.0,82.0,neg,NaN
22,1209600.0,84.0,neg,NaN
23,1209600.0,86.0,pos,NaN
24,1209600.0,134.0,neg,NaN
25,1209600.0,144.0,neg,NaN
26,1209600.0,166.0,neg,NaN
27,1209600.0,236.0,neg,NaN
28,1209600.0,252.0,neg,NaN
29,1209600.0,276.0,neg,NaN
30,1209600.0,320.0,neg,NaN
31,1209600.0,340.0,neg,NaN
32,1209600.0,350.0,neg,NaN
33,1209600.0,482.0,neg,NaN

In [144]:
data = {
    'Batch Size': [2, 4, 2, 4, 8],
    'Hardware': ['A100', 'A100', 'A100', 'A100', 'A300'],
    'Precision': ['fp15', 'fp16', 'fp15', 'fp18', 'fp19'],
    'LLM': ['granite-13b', 'granite-13b', 'llama2-7b', 'llama2-7b', 'llama2-7b'],
    'Throughput': [1367, 2184, 2012, 2936, 3813]
}

df = pd.DataFrame(data)
display(df)

df_wide = df.pivot(
    index=['Batch Size', 'Hardware', 'Precision'],
    columns='LLM',
    values='Throughput'
)

display(df_wide)

# Rename columns
df_wide.columns = [f"Throughput {col}" for col in df_wide.columns]

# Flatten the index to get a clean table
df_wide = df_wide.reset_index()

df_wide

   Batch Size Hardware Precision          LLM  Throughput
0           2     A100      fp15  granite-13b        1367
1           4     A100      fp16  granite-13b        2184
2           2     A100      fp15    llama2-7b        2012
3           4     A100      fp18    llama2-7b        2936
4           8     A300      fp19    llama2-7b        3813

LLM                            granite-13b  llama2-7b
Batch Size Hardware Precision
2          A100     fp15            1367.0     2012.0
4          A100     fp16            2184.0        NaN
                    fp18               NaN     2936.0
8          A300     fp19               NaN     3813.0

   Batch Size Hardware Precision  Throughput granite-13b  Throughput llama2-7b
0           2     A100      fp15                  1367.0                2012.0
1           4     A100      fp16                  2184.0                   NaN
2           4     A100      fp18                     NaN                2936.0
3           8     A300      fp19                     NaN                3813.0

In [219]:
dense_dfs_path = './dense_dfs/'

transform_binary_feature_table = pd.DataFrame(columns=['dataset_id', 'original_num_rows', 'final_num_rows', 'nan_percentage'])

tabArenaURL = 'https://raw.githubusercontent.com/TabArena/tabarena_dataset_curation/refs/heads/main/dataset_creation_scripts/metadata/tabarena_dataset_metadata.csv'
iterator = TabArenaIterator(tabArenaURL)
for row, df in iterator:
    print(row['dataset_id'])
    dense_df_path = dense_dfs_path+str(row['dataset_id'])+'.csv'

    # Check if dataset is one of the dense_dfs
    if os.path.isfile(dense_df_path):
        print('exists')
        # Read the dense_df
        dense_df = pd.read_csv(dense_df_path)

        # Find the binary feature
        binary_feature = final_table[final_table['dataset_id'] == row['dataset_id']]['binary_feature'].values[0]

        # If the dense_df has binary feature 
        if binary_feature != None:

             # In case the binary feature has nan drop those rows
            dense_df = dense_df.dropna(subset=binary_feature)

            # Featurization
            df_wide = dense_df.pivot(
                index=dense_df.drop(columns=[binary_feature, row['target_feature']]),
                columns=binary_feature,
                values=row['target_feature']
            )

            # Rename columns as 'target_feature binary_feature_val_A' and 'target_feature binary_feature_val_B'
            df_wide.columns = [f"{row['target_feature']} {col}" for col in df_wide.columns]

            # Flatten the index to get a clean table
            df_wide = df_wide.reset_index()

            # Save the transformed df
            df_wide.to_csv('dense_dfs_with_transformed_binary_feature/'+str(row['dataset_id'])+'.csv')

            # Find the transformed binary columns
            binary_columns = list(filter(lambda x: row['target_feature'] in x,  df_wide.columns.values))

            # sum the percentage of nans of two colummns
            nan_percentage = np.sum(df_wide[binary_columns].isnull().mean().values * 100) / 2

            # Append the information about the df
            transform_binary_feature_table.loc[len(transform_binary_feature_table)] = {'dataset_id': row['dataset_id'],
                                                                                        'original_num_rows' : len(dense_df),
                                                                                        'final_num_rows': len(df_wide),
                                                                                        'nan_percentage': nan_percentage}
    print()

46904
exists

46905
exists

46906

46907
exists

46908
exists

46910
exists

46911
exists

46912
exists

46913

46915
exists

46916

46917

46918
exists

46919
exists

46920
exists

46921

46922

46923
exists

46924
exists

46927
exists

46928
exists

46929
exists

46930

46931
exists

46932
exists

46933
exists

46934

46935
exists

46937
exists

46938
exists

46939

46940
exists

46941

46942
exists

46980
exists

46969
exists

46947
exists

46949

46950

46952

46953
exists

46954

46955

46956
exists

46958
exists

46960
exists

46961

46962

46963
exists

46964
exists

46979

In [220]:
transform_binary_feature_table

    dataset_id  original_num_rows  final_num_rows  nan_percentage
0        46908                 35              34       48.529412
1        46910               2533            2187       42.089620
2        46911                723             405       10.740741
3        46912                255             201       36.567164
4        46915                625             444       29.617117
5        46918                164             114       28.070175
6        46919                187             106       11.792453
7        46920               8960            8219       45.492152
8        46924               4761            3365       29.257058
9        46927                176             132       33.333333
10       46929                323             323       50.000000
11       46931                986             769       35.890767
12       46932                184             184       50.000000
13       46933                 63              42       25.000000
14       46935               1731            1179       26.590331
15       46937                178             100       11.000000
16       46938                444             291       23.711340
17       46940                 67              56       40.178571
18       46942               2812            2665       47.242026
19       46980                 37              24       22.916667
20       46969                 69              43       19.767442
21       46947                374             290       35.517241
22       46953                 53              44       39.772727
23       46956                 53              33       19.696970
24       46960                175             124       29.435484
25       46963                558             457       38.949672
26       46964               2368            2028       41.617357

In [221]:
joined_table = pd.merge(final_table, transform_binary_feature_table, how='left', on='dataset_id')
joined_table

,dataset_id,dataset_name,original_number_features,final_number_features,original_number_rows,final_number_rows,original_density,final_density,binary_feature,initial_XGB_r2,...,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_r2,final_NN_TORCH_accuracy,final_NN_TORCH_normalized_accuracy,final_improvement_xgb,final_improvement_accuracy,final_improvement_r2,original_num_rows,final_num_rows,nan_percentage
0,46904,airfoil_self_noise,5,4,1503,1503,1.051902e-03,0.110450,None,0.939926,...,NaN,0.945005,NaN,NaN,-1.022182,NaN,-1.578600,NaN,NaN,NaN
1,46905,Amazon_employee_access,9,1,32769,67,5.433146e-21,1.000000,None,NaN,...,0.886888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,46906,anneal,38,13,886,8,6.763895e-16,0.125000,bl,NaN,...,0.990741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,46907,Another-Dataset-on-used-Fiat-500,7,3,1515,34,5.646737e-10,0.354167,None,0.825045,...,NaN,-0.104609,NaN,NaN,-36.919769,NaN,120.100049,NaN,NaN,NaN
4,46908,APSFailure,170,3,76000,52,0.000000e+00,0.866667,ch_000,NaN,...,0.985175,NaN,0.812500,0.625000,-36.677924,0.000000,NaN,35.0,34.0,48.529412
5,46910,bank-marketing,13,8,44905,2533,5.349773e-12,0.183232,default,NaN,...,0.782218,NaN,0.856579,0.713158,-8.952359,-0.743494,NaN,2533.0,2187.0,42.089620
6,46911,Bank_Customer_Churn,10,6,10000,723,4.608577e-12,0.684659,gender,NaN,...,0.699333,NaN,0.815668,0.631336,-5.859118,4.195804,NaN,723.0,405.0,10.740741
7,46912,Bioresponse,1776,11,3751,255,0.000000e+00,0.124512,D1216,NaN,...,0.516874,NaN,0.545455,0.090909,-70.480761,46.153846,NaN,255.0,201.0,36.567164
8,46913,blood-transfusion-service-center,4,2,502,188,1.906424e-04,0.183773,None,NaN,...,0.555556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,46915,churn,19,5,5000,625,2.774980e-36,0.248016,international_plan,NaN,...,0.826667,NaN,0.739362,0.478723,-54.172281,-15.384615,NaN,625.0,444.0,29.617117
10,46916,coil2000_insurance_policies,85,7,8261,29,4.188386e-67,0.100694,contributionBicyclePolicies,NaN,...,0.879199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,46917,concrete_compressive_strength,8,2,996,452,3.038551e-15,0.208295,None,0.898137,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,46918,credit-g,20,7,1000,164,1.403353e-13,0.189815,people_liable,NaN,...,0.566667,NaN,0.600000,0.200000,-60.000000,16.666667,NaN,164.0,114.0,28.070175
13,46919,credit_card_clients_default,23,4,29944,187,4.928384e-57,0.333929,SEX,NaN,...,0.632222,NaN,0.701754,0.403509,-25.521351,14.814815,NaN,187.0,106.0,11.792453
14,46920,customer_satisfaction_in_airline,21,8,129880,8960,1.861241e-18,0.115226,CustomerType,NaN,...,0.906683,NaN,0.890625,0.781250,-8.261264,6.666667,NaN,8960.0,8219.0,45.492152
15,46921,diabetes,8,2,768,283,1.117498e-13,0.354193,None,NaN,...,0.437229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,46922,Diabetes130US,47,9,71518,7,7.578438e-37,0.109375,tolbutamide,NaN,...,0.820656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,46923,diamonds,9,3,53595,276,2.616387e-13,0.985714,None,0.980541,...,NaN,-0.066406,NaN,NaN,-97.674970,NaN,391.282534,NaN,NaN,NaN
18,46924,E-CommereShippingData,10,7,10999,4761,9.032578e-09,0.220417,Gender,NaN,...,0.307273,NaN,0.594822,0.189643,-45.282373,-10.612245,NaN,4761.0,3365.0,29.257058
19,46927,Fitness_Club,6,4,1499,176,1.051149e-05,0.110276,time,NaN,...,0.555556,NaN,0.792453,0.584906,10.591406,0.000000,NaN,176.0,132.0,33.333333
20,46928,Food_Delivery_Time,9,4,45242,3221,5.407391e-16,0.326806,None,0.377846,...,NaN,0.390429,NaN,NaN,29.370052,NaN,20.128306,NaN,NaN,NaN
21,46929,GiveMeSomeCredit,10,3,149354,323,1.066472e-19,0.119453,FinancialDistressNextTwoYears,NaN,...,0.868844,NaN,0.639175,0.278351,-101.183463,2800.000000,NaN,323.0,323.0,50.000000
22,46930,hazelnut-spread-contaminant-detection,30,1,2400,781,4.281294e-90,1.000000,None,NaN,...,0.822222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,46931,healthcare_insurance_expenses,6,5,1335,986,5.399227e-04,0.218528,sex,0.807423,...,NaN,0.630632,NaN,NaN,-19.913625,NaN,2.475043,986.0,769.0,35.890767
24,46932,heloc,23,3,9871,184,1.483257e-35,0.135294,RiskPerformance,NaN,...,0.435946,NaN,0.803571,0.607143,39.473959,0.000000,NaN,184.0,184.0,50.000000
25,46933,hiva_agnostic,1617,9,3825,63,0.000000e+00,0.123047,molecule_structure_property_534,NaN,...,0.953206,NaN,0.947368,0.921053,-3.373206,0.000000,NaN,63.0,42.0,25.000000
26,46934,houses,8,2,20640,11032,5.234241e-22,0.251367,None,0.849217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,46935,HR_Analytics_Job_Change_of_Data_Scientists,12,6,19084,1731,5.308890e-10,0.183992,relevent_experience,NaN,...,0.590118,NaN,0.732692,0.465385,-23.811107,-2.542373,NaN,1731.0,1179.0,26.590331
28,46937,in_vehicle_coupon_recommendation,24,9,12587,178,1.445597e-11,0.154514,expiration,NaN,...,0.490804,NaN,0.518519,0.037037,-63.137300,80.000000,NaN,178.0,100.0,11.000000
29,46938,Is-this-a-good-customer,13,7,1723,444,1.335653e-10,0.205556,sex,NaN,...,0.771760,NaN,0.917910,0.835821,13.417166,0.000000,NaN,444.0,291.0,23.711340
30,46939,kddcup09_appetency,212,8,50000,14,0.000000e+00,0.109375,Var2,NaN,...,0.962133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,46940,Marketing_Campaign,25,8,2039,67,3.460081e-32,0.116319,AcceptedCmp3,NaN,...,0.773810,NaN,0.619048,0.238095,-55.555556,28.571429,NaN,67.0,56.0,40.178571
32,46941,maternal_health_risk,6,2,416,40,7.372958e-06,0.312500,None,NaN,...,0.463934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,46942,miami_housing,15,4,13776,2812,1.011417e-44,0.244097,avno60plus,0.922270,...,NaN,0.142900,NaN,NaN,-67.106808,NaN,52.894769,2812.0,2665.0,47.242026
34,46980,MIC,111,5,1699,37,1.038332e-68,0.228395,SEX,NaN,...,0.858824,NaN,0.250000,0.142857,-29.030186,76.923077,NaN,37.0,24.0,22.916667
35,46969,NATICUSdroid,86,9,7395,69,9.557813e-23,0.134766,android.permission.ACCESS_LOCATION_EXTRA_COMMANDS,NaN,...,0.873665,NaN,0.952381,0.904762,-18.325825,-26.666667,NaN,69.0,43.0,19.767442
36,46947,online_shoppers_intention,17,5,12205,374,1.309373e-29,0.144290,Weekend,NaN,...,0.800487,NaN,0.849558,0.699115,-12.781567,0.000000,NaN,374.0,290.0,35.517241
37,46949,physiochemical_protein,9,1,43974,341,4.142389e-35,1.000000,None,0.645328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,46950,polish_companies_bankruptcy,64,1,5850,3255,9.503573e-236,1.000307,None,NaN,...,0.901861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,46952,qsar-biodeg,41,5,1051,15,2.447264e-63,0.156250,Presence_CBr_At_Dist1,NaN,...,0.728707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,46953,QSAR-TID-11,1024,9,5259,53,2.925416e-305,0.103516,FCFP6_1024_342,0.724764,...,NaN,-0.160186,NaN,NaN,-102.865327,NaN,-671.353974,53.0,44.0,39.772727
41,46954,QSAR_fish_toxicity,6,2,774,23,7.633914e-10,0.657143,None,0.544628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,46955,SDSS17,11,2,78053,6000,2.075436e-42,1.000000,None,NaN,...,0.955223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,46956,seismic-bumps,15,6,2578,53,9.400295e-18,0.184028,seismic,NaN,...,0.868557,NaN,0.875000,0.750000,-12.874251,0.000000,NaN,53.0,33.0,19.696970
44,46958,splice,60,7,3005,2519,6.838044e-38,0.153748,None,NaN,...,0.907524,NaN,0.628307,0.442460,-60.721647,-21.195652,NaN,NaN,NaN,NaN
45,46960,students_dropout_and_academic_success,36,9,4424,175,1.290519e-40,0.113932,Daytimeevening_attendance,NaN,...,0.644202,NaN,0.603774,0.405660,-49.500621,-26.470588,NaN,175.0,124.0,29.435484
46,46961,superconductivity,81,2,15170,45,3.872284e-287,0.714286,None,0.920797,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,46962,taiwanese_bankruptcy_prediction,94,2,6819,389,0.000000e+00,0.510499,Liability_Assets_Flag,NaN,...,0.931574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,46963,website_phishing,9,8,676,558,7.727481e-02,0.191358,age_of_domain,NaN,...,0.837438,NaN,0.803571,0.705357,-23.090523,-5.333333,NaN,558.0,457.0,38.949672
49,46964,wine_quality,12,3,5320,2368,4.506093e-22,0.125503,wine_color,0.467736,...,NaN,0.045309,NaN,NaN,-88.861654,NaN,13.031585,2368.0,2028.0,41.617357
50,46979,jm1,21,2,8824,227,3.679058e-50,0.137576,None,NaN,...,0.621555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [222]:
selected_df = joined_table[['dataset_id', 'original_density', 'final_density', 'nan_percentage']]
selected_df

    dataset_id  original_density  final_density  nan_percentage
0        46904      1.051902e-03       0.110450             NaN
1        46905      5.433146e-21       1.000000             NaN
2        46906      6.763895e-16       0.125000             NaN
3        46907      5.646737e-10       0.354167             NaN
4        46908      0.000000e+00       0.866667       48.529412
5        46910      5.349773e-12       0.183232       42.089620
6        46911      4.608577e-12       0.684659       10.740741
7        46912      0.000000e+00       0.124512       36.567164
8        46913      1.906424e-04       0.183773             NaN
9        46915      2.774980e-36       0.248016       29.617117
10       46916      4.188386e-67       0.100694             NaN
11       46917      3.038551e-15       0.208295             NaN
12       46918      1.403353e-13       0.189815       28.070175
13       46919      4.928384e-57       0.333929       11.792453
14       46920      1.861241e-18       0.115226       45.492152
15       46921      1.117498e-13       0.354193             NaN
16       46922      7.578438e-37       0.109375             NaN
17       46923      2.616387e-13       0.985714             NaN
18       46924      9.032578e-09       0.220417       29.257058
19       46927      1.051149e-05       0.110276       33.333333
20       46928      5.407391e-16       0.326806             NaN
21       46929      1.066472e-19       0.119453       50.000000
22       46930      4.281294e-90       1.000000             NaN
23       46931      5.399227e-04       0.218528       35.890767
24       46932      1.483257e-35       0.135294       50.000000
25       46933      0.000000e+00       0.123047       25.000000
26       46934      5.234241e-22       0.251367             NaN
27       46935      5.308890e-10       0.183992       26.590331
28       46937      1.445597e-11       0.154514       11.000000
29       46938      1.335653e-10       0.205556       23.711340
30       46939      0.000000e+00       0.109375             NaN
31       46940      3.460081e-32       0.116319       40.178571
32       46941      7.372958e-06       0.312500             NaN
33       46942      1.011417e-44       0.244097       47.242026
34       46980      1.038332e-68       0.228395       22.916667
35       46969      9.557813e-23       0.134766       19.767442
36       46947      1.309373e-29       0.144290       35.517241
37       46949      4.142389e-35       1.000000             NaN
38       46950     9.503573e-236       1.000307             NaN
39       46952      2.447264e-63       0.156250             NaN
40       46953     2.925416e-305       0.103516       39.772727
41       46954      7.633914e-10       0.657143             NaN
42       46955      2.075436e-42       1.000000             NaN
43       46956      9.400295e-18       0.184028       19.696970
44       46958      6.838044e-38       0.153748             NaN
45       46960      1.290519e-40       0.113932       29.435484
46       46961     3.872284e-287       0.714286             NaN
47       46962      0.000000e+00       0.510499             NaN
48       46963      7.727481e-02       0.191358       38.949672
49       46964      4.506093e-22       0.125503       41.617357
50       46979      3.679058e-50       0.137576             NaN

# Comparison best-medium preset

In [2]:
import pandas as pd
df_beste_preset = pd.read_csv('./final_table_best_preset.csv')[['dataset_id', 'initial_XGB_r2', 'final_XGB_r2', 'initial_XGB_normalized_accuracy', 'final_XGB_normalized_accuracy', 
                                                            'initial_NN_TORCH_r2', 'final_NN_TORCH_r2', 'initial_NN_TORCH_normalized_accuracy', 'final_NN_TORCH_normalized_accuracy']]
df_medium_preset = pd.read_csv('./final_table_medium_preset.csv')[['dataset_id', 'initial_XGB_r2', 'final_XGB_r2', 'initial_XGB_normalized_accuracy', 'final_XGB_normalized_accuracy', 
                                                            'initial_NN_TORCH_r2', 'final_NN_TORCH_r2', 'initial_NN_TORCH_normalized_accuracy', 'final_NN_TORCH_normalized_accuracy']]
df_medium_preset

,dataset_id,initial_XGB_r2,final_XGB_r2,initial_XGB_normalized_accuracy,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,final_NN_TORCH_r2,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_normalized_accuracy
0,46904,0.939926,0.930319,NaN,NaN,0.946526,0.945005,NaN,NaN
1,46905,NaN,NaN,0.888312,NaN,NaN,NaN,0.886888,NaN
2,46906,NaN,NaN,0.986111,NaN,NaN,NaN,0.990741,NaN
3,46907,0.825045,0.520440,NaN,NaN,0.831274,-0.104609,NaN,NaN
4,46908,NaN,NaN,0.987018,0.625000,NaN,NaN,0.985175,0.625000
5,46910,NaN,NaN,0.777499,0.707895,NaN,NaN,0.782218,0.713158
6,46911,NaN,NaN,0.700000,0.658986,NaN,NaN,0.699333,0.631336
7,46912,NaN,NaN,0.571936,0.168831,NaN,NaN,0.516874,0.090909
8,46913,NaN,NaN,0.448889,NaN,NaN,NaN,0.555556,NaN
9,46915,NaN,NaN,0.905333,0.414894,NaN,NaN,0.826667,0.478723
10,46916,NaN,NaN,0.883950,NaN,NaN,NaN,0.879199,NaN
11,46917,0.898137,NaN,NaN,NaN,0.918552,NaN,NaN,NaN
12,46918,NaN,NaN,0.600000,0.240000,NaN,NaN,0.566667,0.200000
13,46919,NaN,NaN,0.636000,0.473684,NaN,NaN,0.632222,0.403509
14,46920,NaN,NaN,0.912432,0.837054,NaN,NaN,0.906683,0.781250
15,46921,NaN,NaN,0.471861,NaN,NaN,NaN,0.437229,NaN
16,46922,NaN,NaN,0.821588,NaN,NaN,NaN,0.820656,NaN
17,46923,0.980541,0.022798,NaN,NaN,0.975334,-0.066406,NaN,NaN
18,46924,NaN,NaN,0.313333,0.171449,NaN,NaN,0.307273,0.189643
19,46927,NaN,NaN,0.528889,0.584906,NaN,NaN,0.555556,0.584906
20,46928,0.377846,0.488820,NaN,NaN,0.294570,0.390429,NaN,NaN
21,46929,NaN,NaN,0.871111,-0.010309,NaN,NaN,0.868844,0.278351
22,46930,NaN,NaN,0.805556,NaN,NaN,NaN,0.822222,NaN
23,46931,0.807423,0.646636,NaN,NaN,0.800976,0.630632,NaN,NaN
24,46932,NaN,NaN,0.435309,0.607143,NaN,NaN,0.435946,0.607143
25,46933,NaN,NaN,0.953206,0.921053,NaN,NaN,0.953206,0.921053
26,46934,0.849217,NaN,NaN,NaN,0.830619,NaN,NaN,NaN
27,46935,NaN,NaN,0.595685,0.453846,NaN,NaN,0.590118,0.465385
28,46937,NaN,NaN,0.502365,0.185185,NaN,NaN,0.490804,0.037037
29,46938,NaN,NaN,0.736944,0.835821,NaN,NaN,0.771760,0.835821
30,46939,NaN,NaN,0.962800,NaN,NaN,NaN,0.962133,NaN
31,46940,NaN,NaN,0.750000,0.333333,NaN,NaN,0.773810,0.238095
32,46941,NaN,NaN,0.695082,NaN,NaN,NaN,0.463934,NaN
33,46942,0.922270,0.303364,NaN,NaN,0.913591,0.142900,NaN,NaN
34,46980,NaN,NaN,0.872269,0.619048,NaN,NaN,0.858824,0.142857
35,46969,NaN,NaN,0.874555,0.714286,NaN,NaN,0.873665,0.904762
36,46947,NaN,NaN,0.801568,0.699115,NaN,NaN,0.800487,0.699115
37,46949,0.645328,NaN,NaN,NaN,0.610251,NaN,NaN,NaN
38,46950,NaN,NaN,0.950367,NaN,NaN,NaN,0.901861,NaN
39,46952,NaN,NaN,0.665615,NaN,NaN,NaN,0.728707,NaN
40,46953,0.724764,-0.020767,NaN,NaN,0.733659,-0.160186,NaN,NaN
41,46954,0.544628,NaN,NaN,NaN,0.535097,NaN,NaN,NaN
42,46955,NaN,NaN,0.965024,NaN,NaN,NaN,0.952212,NaN
43,46956,NaN,NaN,0.860825,0.750000,NaN,NaN,0.868557,0.750000
44,46958,NaN,NaN,0.929467,0.365079,NaN,NaN,0.907524,0.442460
45,46960,NaN,NaN,0.635166,0.320755,NaN,NaN,0.644202,0.405660
46,46961,0.920797,NaN,NaN,NaN,0.912115,NaN,NaN,NaN
47,46962,NaN,NaN,0.933529,NaN,NaN,NaN,0.931574,NaN
48,46963,NaN,NaN,0.870690,0.669643,NaN,NaN,0.837438,0.705357
49,46964,0.467736,0.052098,NaN,NaN,0.352707,0.045309,NaN,NaN
50,46979,NaN,NaN,0.618494,NaN,NaN,NaN,0.621555,NaN

In [19]:
df_beste_preset.describe().iloc[[1]]

,dataset_id,initial_XGB_r2,final_XGB_r2,initial_XGB_normalized_accuracy,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,final_NN_TORCH_r2,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_normalized_accuracy
mean,46935.27451,0.778329,0.328204,0.762171,0.520107,0.757667,0.276145,0.75682,0.509077

In [18]:
df_medium_preset.describe().iloc[[1]]

,dataset_id,initial_XGB_r2,final_XGB_r2,initial_XGB_normalized_accuracy,final_XGB_normalized_accuracy,initial_NN_TORCH_r2,final_NN_TORCH_r2,initial_NN_TORCH_normalized_accuracy,final_NN_TORCH_normalized_accuracy
mean,46935.27451,0.76182,0.367964,0.755757,0.514446,0.742713,0.227884,0.747587,0.50548

In [3]:
import plotly.graph_objects as go

fig = go.Figure()
# Add traces
fig.add_trace(go.Scatter(x=df_beste_preset['dataset_id'], y=df_beste_preset['final_XGB_r2'],
                    mode='markers',
                    name='best_final_XGB_r2'))
fig.add_trace(go.Scatter(x=df_medium_preset['dataset_id'], y=df_medium_preset['final_XGB_r2'],
                    mode='markers',
                    name='medium_final_XGB_r2'))
fig.show()

In [4]:
import plotly.graph_objects as go

fig = go.Figure()
# Add traces
fig.add_trace(go.Scatter(x=df_beste_preset['dataset_id'], y=df_beste_preset['final_XGB_normalized_accuracy'],
                    mode='markers',
                    name='best_final_XGB_normalized_accuracy'))
fig.add_trace(go.Scatter(x=df_medium_preset['dataset_id'], y=df_medium_preset['final_XGB_normalized_accuracy'],
                    mode='markers',
                    name='medium_final_XGB_normalized_accuracy'))
fig.show()

In [5]:
import plotly.graph_objects as go

fig = go.Figure()
# Add traces
fig.add_trace(go.Scatter(x=df_beste_preset['dataset_id'], y=df_beste_preset['final_NN_TORCH_r2'],
                    mode='markers',
                    name='best_final_NN_TORCH_r2'))
fig.add_trace(go.Scatter(x=df_medium_preset['dataset_id'], y=df_medium_preset['final_NN_TORCH_r2'],
                    mode='markers',
                    name='medium_final_NN_TORCH_r2'))
fig.show()

In [6]:
import plotly.graph_objects as go

fig = go.Figure()
# Add traces
fig.add_trace(go.Scatter(x=df_beste_preset['dataset_id'], y=df_beste_preset['final_NN_TORCH_normalized_accuracy'],
                    mode='markers',
                    name='best_final_NN_TORCH_normalized_accuracy'))
fig.add_trace(go.Scatter(x=df_medium_preset['dataset_id'], y=df_medium_preset['final_NN_TORCH_normalized_accuracy'],
                    mode='markers',
                    name='medium_final_NN_TORCH_normalized_accuracy'))
fig.show()